//
//  ConfigModel.h
//  QSMY
//
//  Created by Eci on 13-12-28.
//  Copyright (c) 2013年 thedream. All rights reserved.
//

#ifndef __QSMY__ConfigModel__
#define __QSMY__ConfigModel__

#define DEFAULT_SFX "default_sfx"
#define TALKING_DATA_APP_ID "analytics_app_id"
#define BATTLE_SPEEDUP "battle_speed_up"
#define BATTLE_SPEED_NORMAL "battle_speed_normal"
#define MAIN_BUTTON_SOUND_KEY "main_button_sfx"
#define LEVEL_UP_SOUND_KEY "user_lvup_sfx"
#define DESTINY_UPGRADE_RATE "destiny_upgrade_rate"	
#define EQUIP_GROW_RATIO "equip_grow_ratio"
#define GUILD_REFRESH_INTERVAL "GUILD_REFRESH_INTERVAL"
#define GUILD_OVERLORD_COINS_DIVISOR "GUILD_OVERLORD_COINS_DIVISOR"
#define GUILD_APPLICATION_MAX "GUILD_APPLICATION_MAX"
#define GUILD_MEMBER_MAX "GUILD_MEMBER_MAX"
#define GUILD_QUESTION_INTERVAL "GUILD_QUESTION_INTERVAL"
#define GUILD_MAX_OVERLORD_COUNT "GUILD_MAX_OVERLORD_COUNT"
#define GUILD_MAX_CHIVALRY_COUNT "GUILD_MAX_CHIVALRY_COUNT"
#define GUILD_CREATE_CONDITION_VIPLV "GUILD_CREATE_CONDITION_VIPLV"
#define GUILD_CREATE_CONDITION_POINT "GUILD_CREATE_CONDITION_POINT"
#define ITEM_CHICKEN "ITEM_CHICKEN"
#define ITEM_NEILIDAN "ITEM_NEILIDAN"
#define ITEM_CHUANGONGDAN1 "ITEM_CHUANGONGDAN1"
#define ITEM_CHUANGONGDAN2 "ITEM_CHUANGONGDAN2"
#define ITEM_PEIYANGDAN "ITEM_PEIYANGDAN"
#define ITEM_ZHAOMULING "ZHAOMULING_ITEM"
#define ITEM_YIJIDANGQIANGCARD "YIJIDANGQIANGCARD"
#define ITEM_WANFUMOKAICARD "WANFUMOKAICARD"
#define ITEM_SKYLIGHT "ITEM_SKYLIGHT"
#define ITEM_POWER "ITEM_POWER"
#define ITEM_COIN "ITEM_COIN"
#define ITEM_POINT "ITEM_POINT"
#define ITEM_CHANGE_NAME "ITEM_CHANGE_NAME"
#define ITEM_GUILD	"ITEM_GUILD"
#define PRODUCT_POW "PRODUCT_POW"
#define PRODUCT_PVE_EXEC_TIMES "PRODUCT_PVE_EXEC_TIMES"
#define MATCH_LIVE_TIME "MATCH_LIVE_TIME"
#define NOTICE_MIN_SYNC_INTERVAL "NOTICE_MIN_SYNC_INTERVAL"

#define PVE_EXPLORE_ONCE_MORE_VIPLEV	"PVE_EXPLORE_ONCE_MORE_VIPLEV"
#define PVE_RUSH_MIN_VIPLEV				"PVE_RUSH_MIN_VIPLEV"
#define PVE_RUSH_MIN_USEPOINT_VIPLEV	"PVE_RUSH_MIN_USEPOINT_VIPLEV" //此vip等级的玩家可以通过点券跳过扫荡cd
#define PVE_DEFAULT_MAP_ID				"PVE_DEFAULT_MAP_ID"
#define PVE_RUSH_CD_TIME				"PVE_RUSH_CD_TIME"	//cd 10分钟
#define PVE_DEVELOP_ITEM_MIN			"PVE_DEVELOP_ITEM_MIN"

#define PVP_TOPLIST_NUM				"PVP_TOPLIST_NUM"			//TOPlist中显示玩家数
#define PVP_TARGET_RANK_MAX			"PVP_TARGET_RANK_MAX"		//排名上限
#define PVP_UPPER_RANK_NUM			"PVP_UPPER_RANK_NUM"        //可挑战的排名数量
#define PVP_LOWER_RANK_NUM			"PVP_LOWER_RANK_NUM"        //可以看见的身后玩家的数量
#define PVP_RANK_SHOW_BOSS			"PVP_RANK_SHOW_BOSS"		//可看到东皇太一的最低排名
#define PVP_RANK_CHANLLENGE_BOSS	"PVP_RANK_CHANLLENGE_BOSS"  //可挑战东皇太一的最低排名
#define PVP_TARGET_LIST_NUM			"PVP_TARGET_LIST_NUM"			//TOP10+可看到的玩家总数
#define PVP_TARGET_LEVEL_RATIO		"PVP_TARGET_LEVEL_RATIO"		//计算等级系数
#define PVP_ROBOT_FORMATION_INDEX	"PVP_ROBOT_FORMATION_INDEX"		//机器人阵型编号起始
#define PVP_REFRESH_TARGET_ERROR	"PVP_REFRESH_TARGET_ERROR"      //需刷新玩家信息的错误码

#define SKILL_SPECIAL_MAXWARRIOR	"SKILL_SPECIAL_MAXWARRIOR"		//特技弟子最大可能个数

#define TOWER_MAX_NUM				"TOWER_MAX_NUM"					//每日最大闯关次数
#define USER_POWER_REFRESH_INTERVAL	"USER_POWER_REFRESH_INTERVAL"		//体力恢复间隔s
#define ENDUR_REFRESH_INTERVAL	"ENDUR_REFRESH_INTERVAL"							//耐力恢复间隔s
#define WARRIORUP_ITEMID	"WARRIORUP_ITEMID"	//英雄进阶 进阶丹ID

#define WARRIOR_DEV_ONCE_MAX "WARRIOR_DEV_ONCE_MAX"
#define WARRIOR_DEV_COST	"WARRIOR_DEV_COST"
#define WARRIOR_REAL_GRADE_MAX "WARRIOR_REAL_GRADE_MAX"

#define WISH_SKY_LIGHT_NUM_PER_TIME	"WISH_SKY_LIGHT_NUM_PER_TIME"
#define PRIZE_XUENV	"PRIZE_XUENV"

#define HERO_DIALOG_PROB "HERO_DIALOG_PROB"
#define HERO_WARRIOR_DIALOG_PROB "HERO_WARRIOR_DIALOG_PROB"
#define HERO_AUTO_MOVE_INTERVAL "HERO_AUTO_MOVE_INTERVAL"

#define USER_LEVEL_MAX "USER_LEVEL_MAX"

#define VOLUME_SFX	"VOLUME_SFX"
#define VOLUME_BGM	"VOLUME_BGM"
#define DISABLE_SETTING "SETTING_CONFIG"
#define DISABLE_ZZB "DISABLE_ZZB"

#define GUILDBOSS_ATTACK_COST	"GUILDBOSS_ATTACK_COST"
#define GUILDBOSS_FIGHT_COST	"GUILDBOSS_FIGHT_COST"
#define GUILDBOSS_RESCUE_COST	"GUILDBOSS_RESCUE_COST"
#define GUILDBOSS_APPLY_DEADLINE	"GUILDBOSS_APPLY_DEADLINE"
#define	GUILDBOSS_START_TIME	"GUILDBOSS_START_TIME"
#define	GUILDBOSS_BOSS_INTERVAL	"GUILDBOSS_BOSS_INTERVAL"
#define	GUILDBOSS_ROB_INTERVAL	"GUILDBOSS_ROB_INTERVAL"
#define GUILDBOSS_POINTS_COUNT	"GUILDBOSS_POINTS_COUNT"
#define GUILDBOSS_STAR_RATE_NORMAL	"GUILDBOSS_STAR_RATE_NORMAL"
#define GUILDBOSS_STAR_RATE_WOUNDED	"GUILDBOSS_STAR_RATE_WOUNDED"
#define GUILDBOSS_CLOSE_TIME		"GUILDBOSS_CLOSE_TIME"
#define GUILDBOSS_NOTICE_INTERVAL	"GUILDBOSS_NOTICE_INTERVAL"
#define GUILDBOSS_REFRESH_INTERVAL	"GUILDBOSS_REFRESH_INTERVAL"
#define GUILDBOSS_ATTACK_BOSS_CD	"GUILDBOSS_ATTACK_BOSS_CD"
#define GUILDBOSS_ATTACK_ANIMATION_INTERVAL	"GUILDBOSS_ATTACK_ANIMATION_INTERVAL"
#define GUILDBOSS_NOTIFICATION_TIME	"GUILDBOSS_NOTIFICATION_TIME"
#define GUILDBOSS_REFRESH_CD	"GUILDBOSS_REFRESH_CD"
#define GUILDBOSS_APPLY_START_TIME	"GUILDBOSS_APPLY_START_TIME"
#define GUILDBOSS_BOSS_FREE_TIMES	"GUILDBOSS_BOSS_FREE_TIMES"
#define	GUILDBOSS_BOSS_PAYED_TIMES	"GUILDBOSS_BOSS_PAYED_TIMES"
#define	GUILDBOSS_ROB_FREE_TIMES	"GUILDBOSS_ROB_FREE_TIMES"
#define	GUILDBOSS_ROB_PAYED_TIMES	"GUILDBOSS_ROB_PAYED_TIMES"
#define GUILDBOSS_ROB_BLOOD_MAX	"GUILDBOSS_ROB_BLOOD_MAX"
#define GUILDBOSS_ANGER_MAX	"GUILDBOSS_ANGER_MAX"
#define GUILDBOSS_BOSS_PERIOD	"GUILDBOSS_BOSS_PERIOD"
#define GUILDBOSS_ROB_PERIOD	"GUILDBOSS_ROB_PERIOD"
#define GUILDBOSS_RANK_START	"GUILDBOSS_RANK_START"
#define GUILDBOSS_RANK_END	"GUILDBOSS_RANK_END"
#define GUILDBOSS_ROB_PERCENT	"GUILDBOSS_ROB_PERCENT"
#define GUILDBOSS_ROB_BONUS	"GUILDBOSS_ROB_BONUS"
#define GUILDBOSS_MAIL_TIME	"GUILDBOSS_MAIL_TIME"

#define UPDATE_DELAY    "UPDATE_DELAY"
#define SHARE_MAX_COUNT	"SHARE_MAX_COUNT"

#define FRIENDS_REQUEST_REFRESH_INTERVAL	"FRIENDS_REQUEST_REFRESH_INTERVAL"
#define FRIENDS_REFRESH_CD	"FRIENDS_REFRESH_CD"
#define FRIENDS_MESSAGE_CD	"FRIENDS_MESSAGE_CD"
#define TEAM_REVIVAL_PERCENT	"TEAM_REVIVAL_PERCENT"
#define TEAM_RECOVER_PERCENT	"TEAM_RECOVER_PERCENT"
#define	TEAM_RESET_COST	"TEAM_RESET_COST"
#define	TEAM_LEVEL_MULTIPLIER	"TEAM_LEVEL_MULTIPLIER"

#define CHAT_PUSH_INTERVAL_TIME "CHAT_PUSH_INTERVAL_TIME"
#define CHAT_PULL_INTERVAL_TIME "CHAT_PULL_INTERVAL_TIME"
#define CHAT_CHECK_INTERVAL_TIME "CHAT_CHECK_INTERVAL_TIME"
#define CHAT_BUFFER_NUM "CHAT_BUFFER_NUM"
#define CHAT_SHOW_INTERVAL_TIME "CHAT_SHOW_INTERVAL_TIME"
#define MAX_SHARE_TIMES "MAX_SHARE_TIMES"

#define ITEM_CHAT	"ITEM_CHAT"

#include "Model.h"

class HttpHandler;

class ConfigModel :public Model
{
public:
    ConfigModel();
    virtual ~ConfigModel();
    virtual bool init();
    
	void loadGameConfig(const CSVDecoder::CSV &val);
	cocos2d::CCString *getConfigByKey(const char *pKey);
protected:
    friend class HttpHandler;
    void setConfigByKey(const char *pKey, const char *pConfig);
private:
	cocos2d::CCDictionary *m_pDictConfig;
};

#endif /* defined(__QSMY__ConfigModel__) */
