// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_meta_data.proto

#ifndef PROTOBUF_report_5fmeta_5fdata_2eproto__INCLUDED
#define PROTOBUF_report_5fmeta_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace battle {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
void protobuf_AssignDesc_report_5fmeta_5fdata_2eproto();
void protobuf_ShutdownFile_report_5fmeta_5fdata_2eproto();

class report_meta_data;
class hp_unit_meta_data;
class hp_report_meta_data;

// ===================================================================

class report_meta_data : public ::google::protobuf::Message {
 public:
  report_meta_data();
  virtual ~report_meta_data();

  report_meta_data(const report_meta_data& from);

  inline report_meta_data& operator=(const report_meta_data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const report_meta_data& default_instance();

  void Swap(report_meta_data* other);

  // implements Message ----------------------------------------------

  report_meta_data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const report_meta_data& from);
  void MergeFrom(const report_meta_data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required uint32 scene = 2;
  inline bool has_scene() const;
  inline void clear_scene();
  static const int kSceneFieldNumber = 2;
  inline ::google::protobuf::uint32 scene() const;
  inline void set_scene(::google::protobuf::uint32 value);

  // required bool win = 3;
  inline bool has_win() const;
  inline void clear_win();
  static const int kWinFieldNumber = 3;
  inline bool win() const;
  inline void set_win(bool value);

  // required uint32 grade = 4;
  inline bool has_grade() const;
  inline void clear_grade();
  static const int kGradeFieldNumber = 4;
  inline ::google::protobuf::uint32 grade() const;
  inline void set_grade(::google::protobuf::uint32 value);

  // required float fight_percent = 5;
  inline bool has_fight_percent() const;
  inline void clear_fight_percent();
  static const int kFightPercentFieldNumber = 5;
  inline float fight_percent() const;
  inline void set_fight_percent(float value);

  // required bytes content = 6;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 6;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const void* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // @@protoc_insertion_point(class_scope:battle.report_meta_data)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_scene();
  inline void clear_has_scene();
  inline void set_has_win();
  inline void clear_has_win();
  inline void set_has_grade();
  inline void clear_has_grade();
  inline void set_has_fight_percent();
  inline void clear_has_fight_percent();
  inline void set_has_content();
  inline void clear_has_content();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 user_id_;
  ::google::protobuf::uint32 scene_;
  bool win_;
  ::google::protobuf::uint32 grade_;
  ::std::string* content_;
  float fight_percent_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
  friend void protobuf_AssignDesc_report_5fmeta_5fdata_2eproto();
  friend void protobuf_ShutdownFile_report_5fmeta_5fdata_2eproto();

  void InitAsDefaultInstance();
  static report_meta_data* default_instance_;
};
// -------------------------------------------------------------------

class hp_unit_meta_data : public ::google::protobuf::Message {
 public:
  hp_unit_meta_data();
  virtual ~hp_unit_meta_data();

  hp_unit_meta_data(const hp_unit_meta_data& from);

  inline hp_unit_meta_data& operator=(const hp_unit_meta_data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const hp_unit_meta_data& default_instance();

  void Swap(hp_unit_meta_data* other);

  // implements Message ----------------------------------------------

  hp_unit_meta_data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const hp_unit_meta_data& from);
  void MergeFrom(const hp_unit_meta_data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 position = 1;
  inline bool has_position() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 1;
  inline ::google::protobuf::uint32 position() const;
  inline void set_position(::google::protobuf::uint32 value);

  // required uint32 hp = 2;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 2;
  inline ::google::protobuf::uint32 hp() const;
  inline void set_hp(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:battle.hp_unit_meta_data)
 private:
  inline void set_has_position();
  inline void clear_has_position();
  inline void set_has_hp();
  inline void clear_has_hp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 position_;
  ::google::protobuf::uint32 hp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
  friend void protobuf_AssignDesc_report_5fmeta_5fdata_2eproto();
  friend void protobuf_ShutdownFile_report_5fmeta_5fdata_2eproto();

  void InitAsDefaultInstance();
  static hp_unit_meta_data* default_instance_;
};
// -------------------------------------------------------------------

class hp_report_meta_data : public ::google::protobuf::Message {
 public:
  hp_report_meta_data();
  virtual ~hp_report_meta_data();

  hp_report_meta_data(const hp_report_meta_data& from);

  inline hp_report_meta_data& operator=(const hp_report_meta_data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const hp_report_meta_data& default_instance();

  void Swap(hp_report_meta_data* other);

  // implements Message ----------------------------------------------

  hp_report_meta_data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const hp_report_meta_data& from);
  void MergeFrom(const hp_report_meta_data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required uint32 scene = 2;
  inline bool has_scene() const;
  inline void clear_scene();
  static const int kSceneFieldNumber = 2;
  inline ::google::protobuf::uint32 scene() const;
  inline void set_scene(::google::protobuf::uint32 value);

  // required bool win = 3;
  inline bool has_win() const;
  inline void clear_win();
  static const int kWinFieldNumber = 3;
  inline bool win() const;
  inline void set_win(bool value);

  // required uint32 grade = 4;
  inline bool has_grade() const;
  inline void clear_grade();
  static const int kGradeFieldNumber = 4;
  inline ::google::protobuf::uint32 grade() const;
  inline void set_grade(::google::protobuf::uint32 value);

  // required float fight_percent = 5;
  inline bool has_fight_percent() const;
  inline void clear_fight_percent();
  static const int kFightPercentFieldNumber = 5;
  inline float fight_percent() const;
  inline void set_fight_percent(float value);

  // repeated .battle.hp_unit_meta_data winner_units = 6;
  inline int winner_units_size() const;
  inline void clear_winner_units();
  static const int kWinnerUnitsFieldNumber = 6;
  inline const ::battle::hp_unit_meta_data& winner_units(int index) const;
  inline ::battle::hp_unit_meta_data* mutable_winner_units(int index);
  inline ::battle::hp_unit_meta_data* add_winner_units();
  inline const ::google::protobuf::RepeatedPtrField< ::battle::hp_unit_meta_data >&
      winner_units() const;
  inline ::google::protobuf::RepeatedPtrField< ::battle::hp_unit_meta_data >*
      mutable_winner_units();

  // required bytes content = 7;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 7;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const void* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // @@protoc_insertion_point(class_scope:battle.hp_report_meta_data)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_scene();
  inline void clear_has_scene();
  inline void set_has_win();
  inline void clear_has_win();
  inline void set_has_grade();
  inline void clear_has_grade();
  inline void set_has_fight_percent();
  inline void clear_has_fight_percent();
  inline void set_has_content();
  inline void clear_has_content();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 user_id_;
  ::google::protobuf::uint32 scene_;
  bool win_;
  ::google::protobuf::uint32 grade_;
  ::google::protobuf::RepeatedPtrField< ::battle::hp_unit_meta_data > winner_units_;
  ::std::string* content_;
  float fight_percent_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
  friend void protobuf_AssignDesc_report_5fmeta_5fdata_2eproto();
  friend void protobuf_ShutdownFile_report_5fmeta_5fdata_2eproto();

  void InitAsDefaultInstance();
  static hp_report_meta_data* default_instance_;
};
// ===================================================================


// ===================================================================

// report_meta_data

// required uint32 user_id = 1;
inline bool report_meta_data::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void report_meta_data::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void report_meta_data::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void report_meta_data::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 report_meta_data::user_id() const {
  return user_id_;
}
inline void report_meta_data::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required uint32 scene = 2;
inline bool report_meta_data::has_scene() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void report_meta_data::set_has_scene() {
  _has_bits_[0] |= 0x00000002u;
}
inline void report_meta_data::clear_has_scene() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void report_meta_data::clear_scene() {
  scene_ = 0u;
  clear_has_scene();
}
inline ::google::protobuf::uint32 report_meta_data::scene() const {
  return scene_;
}
inline void report_meta_data::set_scene(::google::protobuf::uint32 value) {
  set_has_scene();
  scene_ = value;
}

// required bool win = 3;
inline bool report_meta_data::has_win() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void report_meta_data::set_has_win() {
  _has_bits_[0] |= 0x00000004u;
}
inline void report_meta_data::clear_has_win() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void report_meta_data::clear_win() {
  win_ = false;
  clear_has_win();
}
inline bool report_meta_data::win() const {
  return win_;
}
inline void report_meta_data::set_win(bool value) {
  set_has_win();
  win_ = value;
}

// required uint32 grade = 4;
inline bool report_meta_data::has_grade() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void report_meta_data::set_has_grade() {
  _has_bits_[0] |= 0x00000008u;
}
inline void report_meta_data::clear_has_grade() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void report_meta_data::clear_grade() {
  grade_ = 0u;
  clear_has_grade();
}
inline ::google::protobuf::uint32 report_meta_data::grade() const {
  return grade_;
}
inline void report_meta_data::set_grade(::google::protobuf::uint32 value) {
  set_has_grade();
  grade_ = value;
}

// required float fight_percent = 5;
inline bool report_meta_data::has_fight_percent() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void report_meta_data::set_has_fight_percent() {
  _has_bits_[0] |= 0x00000010u;
}
inline void report_meta_data::clear_has_fight_percent() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void report_meta_data::clear_fight_percent() {
  fight_percent_ = 0;
  clear_has_fight_percent();
}
inline float report_meta_data::fight_percent() const {
  return fight_percent_;
}
inline void report_meta_data::set_fight_percent(float value) {
  set_has_fight_percent();
  fight_percent_ = value;
}

// required bytes content = 6;
inline bool report_meta_data::has_content() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void report_meta_data::set_has_content() {
  _has_bits_[0] |= 0x00000020u;
}
inline void report_meta_data::clear_has_content() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void report_meta_data::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& report_meta_data::content() const {
  return *content_;
}
inline void report_meta_data::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void report_meta_data::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void report_meta_data::set_content(const void* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* report_meta_data::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* report_meta_data::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void report_meta_data::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// hp_unit_meta_data

// required uint32 position = 1;
inline bool hp_unit_meta_data::has_position() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void hp_unit_meta_data::set_has_position() {
  _has_bits_[0] |= 0x00000001u;
}
inline void hp_unit_meta_data::clear_has_position() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void hp_unit_meta_data::clear_position() {
  position_ = 0u;
  clear_has_position();
}
inline ::google::protobuf::uint32 hp_unit_meta_data::position() const {
  return position_;
}
inline void hp_unit_meta_data::set_position(::google::protobuf::uint32 value) {
  set_has_position();
  position_ = value;
}

// required uint32 hp = 2;
inline bool hp_unit_meta_data::has_hp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void hp_unit_meta_data::set_has_hp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void hp_unit_meta_data::clear_has_hp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void hp_unit_meta_data::clear_hp() {
  hp_ = 0u;
  clear_has_hp();
}
inline ::google::protobuf::uint32 hp_unit_meta_data::hp() const {
  return hp_;
}
inline void hp_unit_meta_data::set_hp(::google::protobuf::uint32 value) {
  set_has_hp();
  hp_ = value;
}

// -------------------------------------------------------------------

// hp_report_meta_data

// required uint32 user_id = 1;
inline bool hp_report_meta_data::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void hp_report_meta_data::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void hp_report_meta_data::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void hp_report_meta_data::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 hp_report_meta_data::user_id() const {
  return user_id_;
}
inline void hp_report_meta_data::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required uint32 scene = 2;
inline bool hp_report_meta_data::has_scene() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void hp_report_meta_data::set_has_scene() {
  _has_bits_[0] |= 0x00000002u;
}
inline void hp_report_meta_data::clear_has_scene() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void hp_report_meta_data::clear_scene() {
  scene_ = 0u;
  clear_has_scene();
}
inline ::google::protobuf::uint32 hp_report_meta_data::scene() const {
  return scene_;
}
inline void hp_report_meta_data::set_scene(::google::protobuf::uint32 value) {
  set_has_scene();
  scene_ = value;
}

// required bool win = 3;
inline bool hp_report_meta_data::has_win() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void hp_report_meta_data::set_has_win() {
  _has_bits_[0] |= 0x00000004u;
}
inline void hp_report_meta_data::clear_has_win() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void hp_report_meta_data::clear_win() {
  win_ = false;
  clear_has_win();
}
inline bool hp_report_meta_data::win() const {
  return win_;
}
inline void hp_report_meta_data::set_win(bool value) {
  set_has_win();
  win_ = value;
}

// required uint32 grade = 4;
inline bool hp_report_meta_data::has_grade() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void hp_report_meta_data::set_has_grade() {
  _has_bits_[0] |= 0x00000008u;
}
inline void hp_report_meta_data::clear_has_grade() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void hp_report_meta_data::clear_grade() {
  grade_ = 0u;
  clear_has_grade();
}
inline ::google::protobuf::uint32 hp_report_meta_data::grade() const {
  return grade_;
}
inline void hp_report_meta_data::set_grade(::google::protobuf::uint32 value) {
  set_has_grade();
  grade_ = value;
}

// required float fight_percent = 5;
inline bool hp_report_meta_data::has_fight_percent() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void hp_report_meta_data::set_has_fight_percent() {
  _has_bits_[0] |= 0x00000010u;
}
inline void hp_report_meta_data::clear_has_fight_percent() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void hp_report_meta_data::clear_fight_percent() {
  fight_percent_ = 0;
  clear_has_fight_percent();
}
inline float hp_report_meta_data::fight_percent() const {
  return fight_percent_;
}
inline void hp_report_meta_data::set_fight_percent(float value) {
  set_has_fight_percent();
  fight_percent_ = value;
}

// repeated .battle.hp_unit_meta_data winner_units = 6;
inline int hp_report_meta_data::winner_units_size() const {
  return winner_units_.size();
}
inline void hp_report_meta_data::clear_winner_units() {
  winner_units_.Clear();
}
inline const ::battle::hp_unit_meta_data& hp_report_meta_data::winner_units(int index) const {
  return winner_units_.Get(index);
}
inline ::battle::hp_unit_meta_data* hp_report_meta_data::mutable_winner_units(int index) {
  return winner_units_.Mutable(index);
}
inline ::battle::hp_unit_meta_data* hp_report_meta_data::add_winner_units() {
  return winner_units_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::battle::hp_unit_meta_data >&
hp_report_meta_data::winner_units() const {
  return winner_units_;
}
inline ::google::protobuf::RepeatedPtrField< ::battle::hp_unit_meta_data >*
hp_report_meta_data::mutable_winner_units() {
  return &winner_units_;
}

// required bytes content = 7;
inline bool hp_report_meta_data::has_content() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void hp_report_meta_data::set_has_content() {
  _has_bits_[0] |= 0x00000040u;
}
inline void hp_report_meta_data::clear_has_content() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void hp_report_meta_data::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& hp_report_meta_data::content() const {
  return *content_;
}
inline void hp_report_meta_data::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void hp_report_meta_data::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void hp_report_meta_data::set_content(const void* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* hp_report_meta_data::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* hp_report_meta_data::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void hp_report_meta_data::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace battle

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_report_5fmeta_5fdata_2eproto__INCLUDED
