// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: report_meta_data.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "report_meta_data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace battle {

namespace {

const ::google::protobuf::Descriptor* report_meta_data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  report_meta_data_reflection_ = NULL;
const ::google::protobuf::Descriptor* hp_unit_meta_data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  hp_unit_meta_data_reflection_ = NULL;
const ::google::protobuf::Descriptor* hp_report_meta_data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  hp_report_meta_data_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_report_5fmeta_5fdata_2eproto() {
  protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "report_meta_data.proto");
  GOOGLE_CHECK(file != NULL);
  report_meta_data_descriptor_ = file->message_type(0);
  static const int report_meta_data_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(report_meta_data, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(report_meta_data, scene_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(report_meta_data, win_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(report_meta_data, grade_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(report_meta_data, fight_percent_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(report_meta_data, content_),
  };
  report_meta_data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      report_meta_data_descriptor_,
      report_meta_data::default_instance_,
      report_meta_data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(report_meta_data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(report_meta_data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(report_meta_data));
  hp_unit_meta_data_descriptor_ = file->message_type(1);
  static const int hp_unit_meta_data_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_unit_meta_data, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_unit_meta_data, hp_),
  };
  hp_unit_meta_data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      hp_unit_meta_data_descriptor_,
      hp_unit_meta_data::default_instance_,
      hp_unit_meta_data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_unit_meta_data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_unit_meta_data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(hp_unit_meta_data));
  hp_report_meta_data_descriptor_ = file->message_type(2);
  static const int hp_report_meta_data_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, scene_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, win_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, grade_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, fight_percent_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, winner_units_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, content_),
  };
  hp_report_meta_data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      hp_report_meta_data_descriptor_,
      hp_report_meta_data::default_instance_,
      hp_report_meta_data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hp_report_meta_data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(hp_report_meta_data));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_report_5fmeta_5fdata_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    report_meta_data_descriptor_, &report_meta_data::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    hp_unit_meta_data_descriptor_, &hp_unit_meta_data::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    hp_report_meta_data_descriptor_, &hp_report_meta_data::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_report_5fmeta_5fdata_2eproto() {
  delete report_meta_data::default_instance_;
  delete report_meta_data_reflection_;
  delete hp_unit_meta_data::default_instance_;
  delete hp_unit_meta_data_reflection_;
  delete hp_report_meta_data::default_instance_;
  delete hp_report_meta_data_reflection_;
}

void protobuf_AddDesc_report_5fmeta_5fdata_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026report_meta_data.proto\022\006battle\"v\n\020repo"
    "rt_meta_data\022\017\n\007user_id\030\001 \002(\r\022\r\n\005scene\030\002"
    " \002(\r\022\013\n\003win\030\003 \002(\010\022\r\n\005grade\030\004 \002(\r\022\025\n\rfigh"
    "t_percent\030\005 \002(\002\022\017\n\007content\030\006 \002(\014\"1\n\021hp_u"
    "nit_meta_data\022\020\n\010position\030\001 \002(\r\022\n\n\002hp\030\002 "
    "\002(\r\"\252\001\n\023hp_report_meta_data\022\017\n\007user_id\030\001"
    " \002(\r\022\r\n\005scene\030\002 \002(\r\022\013\n\003win\030\003 \002(\010\022\r\n\005grad"
    "e\030\004 \002(\r\022\025\n\rfight_percent\030\005 \002(\002\022/\n\014winner"
    "_units\030\006 \003(\0132\031.battle.hp_unit_meta_data\022"
    "\017\n\007content\030\007 \002(\014", 376);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "report_meta_data.proto", &protobuf_RegisterTypes);
  report_meta_data::default_instance_ = new report_meta_data();
  hp_unit_meta_data::default_instance_ = new hp_unit_meta_data();
  hp_report_meta_data::default_instance_ = new hp_report_meta_data();
  report_meta_data::default_instance_->InitAsDefaultInstance();
  hp_unit_meta_data::default_instance_->InitAsDefaultInstance();
  hp_report_meta_data::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_report_5fmeta_5fdata_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_report_5fmeta_5fdata_2eproto {
  StaticDescriptorInitializer_report_5fmeta_5fdata_2eproto() {
    protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
  }
} static_descriptor_initializer_report_5fmeta_5fdata_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int report_meta_data::kUserIdFieldNumber;
const int report_meta_data::kSceneFieldNumber;
const int report_meta_data::kWinFieldNumber;
const int report_meta_data::kGradeFieldNumber;
const int report_meta_data::kFightPercentFieldNumber;
const int report_meta_data::kContentFieldNumber;
#endif  // !_MSC_VER

report_meta_data::report_meta_data()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void report_meta_data::InitAsDefaultInstance() {
}

report_meta_data::report_meta_data(const report_meta_data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void report_meta_data::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = 0u;
  scene_ = 0u;
  win_ = false;
  grade_ = 0u;
  fight_percent_ = 0;
  content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

report_meta_data::~report_meta_data() {
  SharedDtor();
}

void report_meta_data::SharedDtor() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (this != default_instance_) {
  }
}

void report_meta_data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* report_meta_data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return report_meta_data_descriptor_;
}

const report_meta_data& report_meta_data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
  return *default_instance_;
}

report_meta_data* report_meta_data::default_instance_ = NULL;

report_meta_data* report_meta_data::New() const {
  return new report_meta_data;
}

void report_meta_data::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = 0u;
    scene_ = 0u;
    win_ = false;
    grade_ = 0u;
    fight_percent_ = 0;
    if (has_content()) {
      if (content_ != &::google::protobuf::internal::kEmptyString) {
        content_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool report_meta_data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_scene;
        break;
      }

      // required uint32 scene = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_scene:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &scene_)));
          set_has_scene();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_win;
        break;
      }

      // required bool win = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_win:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &win_)));
          set_has_win();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_grade;
        break;
      }

      // required uint32 grade = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_grade:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &grade_)));
          set_has_grade();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(45)) goto parse_fight_percent;
        break;
      }

      // required float fight_percent = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_fight_percent:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &fight_percent_)));
          set_has_fight_percent();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_content;
        break;
      }

      // required bytes content = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_content:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_content()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void report_meta_data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // required uint32 scene = 2;
  if (has_scene()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->scene(), output);
  }

  // required bool win = 3;
  if (has_win()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->win(), output);
  }

  // required uint32 grade = 4;
  if (has_grade()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->grade(), output);
  }

  // required float fight_percent = 5;
  if (has_fight_percent()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->fight_percent(), output);
  }

  // required bytes content = 6;
  if (has_content()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      6, this->content(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* report_meta_data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // required uint32 scene = 2;
  if (has_scene()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->scene(), target);
  }

  // required bool win = 3;
  if (has_win()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->win(), target);
  }

  // required uint32 grade = 4;
  if (has_grade()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->grade(), target);
  }

  // required float fight_percent = 5;
  if (has_fight_percent()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->fight_percent(), target);
  }

  // required bytes content = 6;
  if (has_content()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        6, this->content(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int report_meta_data::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

    // required uint32 scene = 2;
    if (has_scene()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->scene());
    }

    // required bool win = 3;
    if (has_win()) {
      total_size += 1 + 1;
    }

    // required uint32 grade = 4;
    if (has_grade()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->grade());
    }

    // required float fight_percent = 5;
    if (has_fight_percent()) {
      total_size += 1 + 4;
    }

    // required bytes content = 6;
    if (has_content()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->content());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void report_meta_data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const report_meta_data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const report_meta_data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void report_meta_data::MergeFrom(const report_meta_data& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_scene()) {
      set_scene(from.scene());
    }
    if (from.has_win()) {
      set_win(from.win());
    }
    if (from.has_grade()) {
      set_grade(from.grade());
    }
    if (from.has_fight_percent()) {
      set_fight_percent(from.fight_percent());
    }
    if (from.has_content()) {
      set_content(from.content());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void report_meta_data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void report_meta_data::CopyFrom(const report_meta_data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool report_meta_data::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003f) != 0x0000003f) return false;

  return true;
}

void report_meta_data::Swap(report_meta_data* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(scene_, other->scene_);
    std::swap(win_, other->win_);
    std::swap(grade_, other->grade_);
    std::swap(fight_percent_, other->fight_percent_);
    std::swap(content_, other->content_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata report_meta_data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = report_meta_data_descriptor_;
  metadata.reflection = report_meta_data_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int hp_unit_meta_data::kPositionFieldNumber;
const int hp_unit_meta_data::kHpFieldNumber;
#endif  // !_MSC_VER

hp_unit_meta_data::hp_unit_meta_data()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void hp_unit_meta_data::InitAsDefaultInstance() {
}

hp_unit_meta_data::hp_unit_meta_data(const hp_unit_meta_data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void hp_unit_meta_data::SharedCtor() {
  _cached_size_ = 0;
  position_ = 0u;
  hp_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

hp_unit_meta_data::~hp_unit_meta_data() {
  SharedDtor();
}

void hp_unit_meta_data::SharedDtor() {
  if (this != default_instance_) {
  }
}

void hp_unit_meta_data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* hp_unit_meta_data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return hp_unit_meta_data_descriptor_;
}

const hp_unit_meta_data& hp_unit_meta_data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
  return *default_instance_;
}

hp_unit_meta_data* hp_unit_meta_data::default_instance_ = NULL;

hp_unit_meta_data* hp_unit_meta_data::New() const {
  return new hp_unit_meta_data;
}

void hp_unit_meta_data::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    position_ = 0u;
    hp_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool hp_unit_meta_data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 position = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &position_)));
          set_has_position();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_hp;
        break;
      }

      // required uint32 hp = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_hp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &hp_)));
          set_has_hp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void hp_unit_meta_data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 position = 1;
  if (has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->position(), output);
  }

  // required uint32 hp = 2;
  if (has_hp()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->hp(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* hp_unit_meta_data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 position = 1;
  if (has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->position(), target);
  }

  // required uint32 hp = 2;
  if (has_hp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->hp(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int hp_unit_meta_data::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 position = 1;
    if (has_position()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->position());
    }

    // required uint32 hp = 2;
    if (has_hp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->hp());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void hp_unit_meta_data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const hp_unit_meta_data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const hp_unit_meta_data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void hp_unit_meta_data::MergeFrom(const hp_unit_meta_data& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_position()) {
      set_position(from.position());
    }
    if (from.has_hp()) {
      set_hp(from.hp());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void hp_unit_meta_data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void hp_unit_meta_data::CopyFrom(const hp_unit_meta_data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool hp_unit_meta_data::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void hp_unit_meta_data::Swap(hp_unit_meta_data* other) {
  if (other != this) {
    std::swap(position_, other->position_);
    std::swap(hp_, other->hp_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata hp_unit_meta_data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = hp_unit_meta_data_descriptor_;
  metadata.reflection = hp_unit_meta_data_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int hp_report_meta_data::kUserIdFieldNumber;
const int hp_report_meta_data::kSceneFieldNumber;
const int hp_report_meta_data::kWinFieldNumber;
const int hp_report_meta_data::kGradeFieldNumber;
const int hp_report_meta_data::kFightPercentFieldNumber;
const int hp_report_meta_data::kWinnerUnitsFieldNumber;
const int hp_report_meta_data::kContentFieldNumber;
#endif  // !_MSC_VER

hp_report_meta_data::hp_report_meta_data()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void hp_report_meta_data::InitAsDefaultInstance() {
}

hp_report_meta_data::hp_report_meta_data(const hp_report_meta_data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void hp_report_meta_data::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = 0u;
  scene_ = 0u;
  win_ = false;
  grade_ = 0u;
  fight_percent_ = 0;
  content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

hp_report_meta_data::~hp_report_meta_data() {
  SharedDtor();
}

void hp_report_meta_data::SharedDtor() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (this != default_instance_) {
  }
}

void hp_report_meta_data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* hp_report_meta_data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return hp_report_meta_data_descriptor_;
}

const hp_report_meta_data& hp_report_meta_data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_report_5fmeta_5fdata_2eproto();
  return *default_instance_;
}

hp_report_meta_data* hp_report_meta_data::default_instance_ = NULL;

hp_report_meta_data* hp_report_meta_data::New() const {
  return new hp_report_meta_data;
}

void hp_report_meta_data::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = 0u;
    scene_ = 0u;
    win_ = false;
    grade_ = 0u;
    fight_percent_ = 0;
    if (has_content()) {
      if (content_ != &::google::protobuf::internal::kEmptyString) {
        content_->clear();
      }
    }
  }
  winner_units_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool hp_report_meta_data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_scene;
        break;
      }

      // required uint32 scene = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_scene:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &scene_)));
          set_has_scene();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_win;
        break;
      }

      // required bool win = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_win:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &win_)));
          set_has_win();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_grade;
        break;
      }

      // required uint32 grade = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_grade:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &grade_)));
          set_has_grade();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(45)) goto parse_fight_percent;
        break;
      }

      // required float fight_percent = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_fight_percent:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &fight_percent_)));
          set_has_fight_percent();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_winner_units;
        break;
      }

      // repeated .battle.hp_unit_meta_data winner_units = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_winner_units:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_winner_units()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_winner_units;
        if (input->ExpectTag(58)) goto parse_content;
        break;
      }

      // required bytes content = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_content:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_content()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void hp_report_meta_data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // required uint32 scene = 2;
  if (has_scene()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->scene(), output);
  }

  // required bool win = 3;
  if (has_win()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->win(), output);
  }

  // required uint32 grade = 4;
  if (has_grade()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->grade(), output);
  }

  // required float fight_percent = 5;
  if (has_fight_percent()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->fight_percent(), output);
  }

  // repeated .battle.hp_unit_meta_data winner_units = 6;
  for (int i = 0; i < this->winner_units_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->winner_units(i), output);
  }

  // required bytes content = 7;
  if (has_content()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      7, this->content(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* hp_report_meta_data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // required uint32 scene = 2;
  if (has_scene()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->scene(), target);
  }

  // required bool win = 3;
  if (has_win()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->win(), target);
  }

  // required uint32 grade = 4;
  if (has_grade()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->grade(), target);
  }

  // required float fight_percent = 5;
  if (has_fight_percent()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->fight_percent(), target);
  }

  // repeated .battle.hp_unit_meta_data winner_units = 6;
  for (int i = 0; i < this->winner_units_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->winner_units(i), target);
  }

  // required bytes content = 7;
  if (has_content()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        7, this->content(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int hp_report_meta_data::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

    // required uint32 scene = 2;
    if (has_scene()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->scene());
    }

    // required bool win = 3;
    if (has_win()) {
      total_size += 1 + 1;
    }

    // required uint32 grade = 4;
    if (has_grade()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->grade());
    }

    // required float fight_percent = 5;
    if (has_fight_percent()) {
      total_size += 1 + 4;
    }

    // required bytes content = 7;
    if (has_content()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->content());
    }

  }
  // repeated .battle.hp_unit_meta_data winner_units = 6;
  total_size += 1 * this->winner_units_size();
  for (int i = 0; i < this->winner_units_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->winner_units(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void hp_report_meta_data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const hp_report_meta_data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const hp_report_meta_data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void hp_report_meta_data::MergeFrom(const hp_report_meta_data& from) {
  GOOGLE_CHECK_NE(&from, this);
  winner_units_.MergeFrom(from.winner_units_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_scene()) {
      set_scene(from.scene());
    }
    if (from.has_win()) {
      set_win(from.win());
    }
    if (from.has_grade()) {
      set_grade(from.grade());
    }
    if (from.has_fight_percent()) {
      set_fight_percent(from.fight_percent());
    }
    if (from.has_content()) {
      set_content(from.content());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void hp_report_meta_data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void hp_report_meta_data::CopyFrom(const hp_report_meta_data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool hp_report_meta_data::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000005f) != 0x0000005f) return false;

  for (int i = 0; i < winner_units_size(); i++) {
    if (!this->winner_units(i).IsInitialized()) return false;
  }
  return true;
}

void hp_report_meta_data::Swap(hp_report_meta_data* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(scene_, other->scene_);
    std::swap(win_, other->win_);
    std::swap(grade_, other->grade_);
    std::swap(fight_percent_, other->fight_percent_);
    winner_units_.Swap(&other->winner_units_);
    std::swap(content_, other->content_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata hp_report_meta_data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = hp_report_meta_data_descriptor_;
  metadata.reflection = hp_report_meta_data_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace battle

// @@protoc_insertion_point(global_scope)
