// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dress.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dress.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cache {

namespace {

const ::google::protobuf::Descriptor* proDress_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proDress_reflection_ = NULL;
const ::google::protobuf::Descriptor* proGetDress_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proGetDress_reflection_ = NULL;
const ::google::protobuf::Descriptor* proGetDresses_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proGetDresses_reflection_ = NULL;
const ::google::protobuf::Descriptor* proGetDressesByWarrior_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proGetDressesByWarrior_reflection_ = NULL;
const ::google::protobuf::Descriptor* proAddDress_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proAddDress_reflection_ = NULL;
const ::google::protobuf::Descriptor* proUpdateDress_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proUpdateDress_reflection_ = NULL;
const ::google::protobuf::Descriptor* proRemoveDress_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proRemoveDress_reflection_ = NULL;
const ::google::protobuf::Descriptor* proDressRes_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proDressRes_reflection_ = NULL;
const ::google::protobuf::Descriptor* proDressesRes_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  proDressesRes_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_dress_2eproto() {
  protobuf_AddDesc_dress_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "dress.proto");
  GOOGLE_CHECK(file != NULL);
  proDress_descriptor_ = file->message_type(0);
  static const int proDress_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDress, dress_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDress, warrior_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDress, level_),
  };
  proDress_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proDress_descriptor_,
      proDress::default_instance_,
      proDress_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDress, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDress, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proDress));
  proGetDress_descriptor_ = file->message_type(1);
  static const int proGetDress_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDress, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDress, dress_id_),
  };
  proGetDress_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proGetDress_descriptor_,
      proGetDress::default_instance_,
      proGetDress_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDress, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDress, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proGetDress));
  proGetDresses_descriptor_ = file->message_type(2);
  static const int proGetDresses_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDresses, user_id_),
  };
  proGetDresses_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proGetDresses_descriptor_,
      proGetDresses::default_instance_,
      proGetDresses_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDresses, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDresses, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proGetDresses));
  proGetDressesByWarrior_descriptor_ = file->message_type(3);
  static const int proGetDressesByWarrior_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDressesByWarrior, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDressesByWarrior, warrior_list_),
  };
  proGetDressesByWarrior_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proGetDressesByWarrior_descriptor_,
      proGetDressesByWarrior::default_instance_,
      proGetDressesByWarrior_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDressesByWarrior, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proGetDressesByWarrior, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proGetDressesByWarrior));
  proAddDress_descriptor_ = file->message_type(4);
  static const int proAddDress_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proAddDress, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proAddDress, dress_),
  };
  proAddDress_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proAddDress_descriptor_,
      proAddDress::default_instance_,
      proAddDress_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proAddDress, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proAddDress, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proAddDress));
  proUpdateDress_descriptor_ = file->message_type(5);
  static const int proUpdateDress_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proUpdateDress, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proUpdateDress, dress_),
  };
  proUpdateDress_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proUpdateDress_descriptor_,
      proUpdateDress::default_instance_,
      proUpdateDress_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proUpdateDress, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proUpdateDress, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proUpdateDress));
  proRemoveDress_descriptor_ = file->message_type(6);
  static const int proRemoveDress_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proRemoveDress, user_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proRemoveDress, dress_id_),
  };
  proRemoveDress_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proRemoveDress_descriptor_,
      proRemoveDress::default_instance_,
      proRemoveDress_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proRemoveDress, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proRemoveDress, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proRemoveDress));
  proDressRes_descriptor_ = file->message_type(7);
  static const int proDressRes_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDressRes, code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDressRes, dress_),
  };
  proDressRes_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proDressRes_descriptor_,
      proDressRes::default_instance_,
      proDressRes_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDressRes, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDressRes, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proDressRes));
  proDressesRes_descriptor_ = file->message_type(8);
  static const int proDressesRes_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDressesRes, code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDressesRes, dresses_),
  };
  proDressesRes_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      proDressesRes_descriptor_,
      proDressesRes::default_instance_,
      proDressesRes_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDressesRes, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(proDressesRes, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(proDressesRes));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_dress_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proDress_descriptor_, &proDress::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proGetDress_descriptor_, &proGetDress::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proGetDresses_descriptor_, &proGetDresses::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proGetDressesByWarrior_descriptor_, &proGetDressesByWarrior::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proAddDress_descriptor_, &proAddDress::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proUpdateDress_descriptor_, &proUpdateDress::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proRemoveDress_descriptor_, &proRemoveDress::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proDressRes_descriptor_, &proDressRes::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    proDressesRes_descriptor_, &proDressesRes::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_dress_2eproto() {
  delete proDress::default_instance_;
  delete proDress_reflection_;
  delete proGetDress::default_instance_;
  delete proGetDress_reflection_;
  delete proGetDresses::default_instance_;
  delete proGetDresses_reflection_;
  delete proGetDressesByWarrior::default_instance_;
  delete proGetDressesByWarrior_reflection_;
  delete proAddDress::default_instance_;
  delete proAddDress_reflection_;
  delete proUpdateDress::default_instance_;
  delete proUpdateDress_reflection_;
  delete proRemoveDress::default_instance_;
  delete proRemoveDress_reflection_;
  delete proDressRes::default_instance_;
  delete proDressRes_reflection_;
  delete proDressesRes::default_instance_;
  delete proDressesRes_reflection_;
}

void protobuf_AddDesc_dress_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013dress.proto\022\005cache\"\?\n\010proDress\022\020\n\010dres"
    "s_id\030\001 \002(\r\022\022\n\nwarrior_id\030\002 \002(\r\022\r\n\005level\030"
    "\003 \002(\r\"0\n\013proGetDress\022\017\n\007user_id\030\001 \002(\r\022\020\n"
    "\010dress_id\030\002 \002(\r\" \n\rproGetDresses\022\017\n\007user"
    "_id\030\001 \002(\r\"\?\n\026proGetDressesByWarrior\022\017\n\007u"
    "ser_id\030\001 \002(\r\022\024\n\014warrior_list\030\002 \003(\r\">\n\013pr"
    "oAddDress\022\017\n\007user_id\030\001 \002(\r\022\036\n\005dress\030\002 \002("
    "\0132\017.cache.proDress\"A\n\016proUpdateDress\022\017\n\007"
    "user_id\030\001 \002(\r\022\036\n\005dress\030\002 \002(\0132\017.cache.pro"
    "Dress\"3\n\016proRemoveDress\022\017\n\007user_id\030\001 \002(\r"
    "\022\020\n\010dress_id\030\002 \002(\r\";\n\013proDressRes\022\014\n\004cod"
    "e\030\001 \002(\r\022\036\n\005dress\030\002 \001(\0132\017.cache.proDress\""
    "\?\n\rproDressesRes\022\014\n\004code\030\001 \002(\r\022 \n\007dresse"
    "s\030\002 \003(\0132\017.cache.proDress", 544);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dress.proto", &protobuf_RegisterTypes);
  proDress::default_instance_ = new proDress();
  proGetDress::default_instance_ = new proGetDress();
  proGetDresses::default_instance_ = new proGetDresses();
  proGetDressesByWarrior::default_instance_ = new proGetDressesByWarrior();
  proAddDress::default_instance_ = new proAddDress();
  proUpdateDress::default_instance_ = new proUpdateDress();
  proRemoveDress::default_instance_ = new proRemoveDress();
  proDressRes::default_instance_ = new proDressRes();
  proDressesRes::default_instance_ = new proDressesRes();
  proDress::default_instance_->InitAsDefaultInstance();
  proGetDress::default_instance_->InitAsDefaultInstance();
  proGetDresses::default_instance_->InitAsDefaultInstance();
  proGetDressesByWarrior::default_instance_->InitAsDefaultInstance();
  proAddDress::default_instance_->InitAsDefaultInstance();
  proUpdateDress::default_instance_->InitAsDefaultInstance();
  proRemoveDress::default_instance_->InitAsDefaultInstance();
  proDressRes::default_instance_->InitAsDefaultInstance();
  proDressesRes::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_dress_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_dress_2eproto {
  StaticDescriptorInitializer_dress_2eproto() {
    protobuf_AddDesc_dress_2eproto();
  }
} static_descriptor_initializer_dress_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int proDress::kDressIdFieldNumber;
const int proDress::kWarriorIdFieldNumber;
const int proDress::kLevelFieldNumber;
#endif  // !_MSC_VER

proDress::proDress()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proDress::InitAsDefaultInstance() {
}

proDress::proDress(const proDress& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proDress::SharedCtor() {
  _cached_size_ = 0;
  dress_id_ = 0u;
  warrior_id_ = 0u;
  level_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proDress::~proDress() {
  SharedDtor();
}

void proDress::SharedDtor() {
  if (this != default_instance_) {
  }
}

void proDress::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proDress::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proDress_descriptor_;
}

const proDress& proDress::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proDress* proDress::default_instance_ = NULL;

proDress* proDress::New() const {
  return new proDress;
}

void proDress::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    dress_id_ = 0u;
    warrior_id_ = 0u;
    level_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proDress::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 dress_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dress_id_)));
          set_has_dress_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_warrior_id;
        break;
      }

      // required uint32 warrior_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_warrior_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &warrior_id_)));
          set_has_warrior_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_level;
        break;
      }

      // required uint32 level = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_level:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &level_)));
          set_has_level();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proDress::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 dress_id = 1;
  if (has_dress_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->dress_id(), output);
  }

  // required uint32 warrior_id = 2;
  if (has_warrior_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->warrior_id(), output);
  }

  // required uint32 level = 3;
  if (has_level()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->level(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proDress::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 dress_id = 1;
  if (has_dress_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->dress_id(), target);
  }

  // required uint32 warrior_id = 2;
  if (has_warrior_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->warrior_id(), target);
  }

  // required uint32 level = 3;
  if (has_level()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->level(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proDress::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 dress_id = 1;
    if (has_dress_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->dress_id());
    }

    // required uint32 warrior_id = 2;
    if (has_warrior_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->warrior_id());
    }

    // required uint32 level = 3;
    if (has_level()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->level());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proDress::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proDress* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proDress*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proDress::MergeFrom(const proDress& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_dress_id()) {
      set_dress_id(from.dress_id());
    }
    if (from.has_warrior_id()) {
      set_warrior_id(from.warrior_id());
    }
    if (from.has_level()) {
      set_level(from.level());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proDress::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proDress::CopyFrom(const proDress& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proDress::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void proDress::Swap(proDress* other) {
  if (other != this) {
    std::swap(dress_id_, other->dress_id_);
    std::swap(warrior_id_, other->warrior_id_);
    std::swap(level_, other->level_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proDress::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proDress_descriptor_;
  metadata.reflection = proDress_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int proGetDress::kUserIdFieldNumber;
const int proGetDress::kDressIdFieldNumber;
#endif  // !_MSC_VER

proGetDress::proGetDress()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proGetDress::InitAsDefaultInstance() {
}

proGetDress::proGetDress(const proGetDress& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proGetDress::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = 0u;
  dress_id_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proGetDress::~proGetDress() {
  SharedDtor();
}

void proGetDress::SharedDtor() {
  if (this != default_instance_) {
  }
}

void proGetDress::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proGetDress::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proGetDress_descriptor_;
}

const proGetDress& proGetDress::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proGetDress* proGetDress::default_instance_ = NULL;

proGetDress* proGetDress::New() const {
  return new proGetDress;
}

void proGetDress::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = 0u;
    dress_id_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proGetDress::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_dress_id;
        break;
      }

      // required uint32 dress_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_dress_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dress_id_)));
          set_has_dress_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proGetDress::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // required uint32 dress_id = 2;
  if (has_dress_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->dress_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proGetDress::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // required uint32 dress_id = 2;
  if (has_dress_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->dress_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proGetDress::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

    // required uint32 dress_id = 2;
    if (has_dress_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->dress_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proGetDress::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proGetDress* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proGetDress*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proGetDress::MergeFrom(const proGetDress& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_dress_id()) {
      set_dress_id(from.dress_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proGetDress::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proGetDress::CopyFrom(const proGetDress& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proGetDress::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void proGetDress::Swap(proGetDress* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(dress_id_, other->dress_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proGetDress::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proGetDress_descriptor_;
  metadata.reflection = proGetDress_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int proGetDresses::kUserIdFieldNumber;
#endif  // !_MSC_VER

proGetDresses::proGetDresses()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proGetDresses::InitAsDefaultInstance() {
}

proGetDresses::proGetDresses(const proGetDresses& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proGetDresses::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proGetDresses::~proGetDresses() {
  SharedDtor();
}

void proGetDresses::SharedDtor() {
  if (this != default_instance_) {
  }
}

void proGetDresses::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proGetDresses::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proGetDresses_descriptor_;
}

const proGetDresses& proGetDresses::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proGetDresses* proGetDresses::default_instance_ = NULL;

proGetDresses* proGetDresses::New() const {
  return new proGetDresses;
}

void proGetDresses::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proGetDresses::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proGetDresses::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proGetDresses::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proGetDresses::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proGetDresses::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proGetDresses* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proGetDresses*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proGetDresses::MergeFrom(const proGetDresses& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proGetDresses::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proGetDresses::CopyFrom(const proGetDresses& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proGetDresses::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void proGetDresses::Swap(proGetDresses* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proGetDresses::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proGetDresses_descriptor_;
  metadata.reflection = proGetDresses_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int proGetDressesByWarrior::kUserIdFieldNumber;
const int proGetDressesByWarrior::kWarriorListFieldNumber;
#endif  // !_MSC_VER

proGetDressesByWarrior::proGetDressesByWarrior()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proGetDressesByWarrior::InitAsDefaultInstance() {
}

proGetDressesByWarrior::proGetDressesByWarrior(const proGetDressesByWarrior& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proGetDressesByWarrior::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proGetDressesByWarrior::~proGetDressesByWarrior() {
  SharedDtor();
}

void proGetDressesByWarrior::SharedDtor() {
  if (this != default_instance_) {
  }
}

void proGetDressesByWarrior::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proGetDressesByWarrior::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proGetDressesByWarrior_descriptor_;
}

const proGetDressesByWarrior& proGetDressesByWarrior::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proGetDressesByWarrior* proGetDressesByWarrior::default_instance_ = NULL;

proGetDressesByWarrior* proGetDressesByWarrior::New() const {
  return new proGetDressesByWarrior;
}

void proGetDressesByWarrior::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = 0u;
  }
  warrior_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proGetDressesByWarrior::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_warrior_list;
        break;
      }

      // repeated uint32 warrior_list = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_warrior_list:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 16, input, this->mutable_warrior_list())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_warrior_list())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_warrior_list;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proGetDressesByWarrior::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // repeated uint32 warrior_list = 2;
  for (int i = 0; i < this->warrior_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      2, this->warrior_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proGetDressesByWarrior::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // repeated uint32 warrior_list = 2;
  for (int i = 0; i < this->warrior_list_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(2, this->warrior_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proGetDressesByWarrior::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

  }
  // repeated uint32 warrior_list = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->warrior_list_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->warrior_list(i));
    }
    total_size += 1 * this->warrior_list_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proGetDressesByWarrior::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proGetDressesByWarrior* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proGetDressesByWarrior*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proGetDressesByWarrior::MergeFrom(const proGetDressesByWarrior& from) {
  GOOGLE_CHECK_NE(&from, this);
  warrior_list_.MergeFrom(from.warrior_list_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proGetDressesByWarrior::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proGetDressesByWarrior::CopyFrom(const proGetDressesByWarrior& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proGetDressesByWarrior::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void proGetDressesByWarrior::Swap(proGetDressesByWarrior* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    warrior_list_.Swap(&other->warrior_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proGetDressesByWarrior::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proGetDressesByWarrior_descriptor_;
  metadata.reflection = proGetDressesByWarrior_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int proAddDress::kUserIdFieldNumber;
const int proAddDress::kDressFieldNumber;
#endif  // !_MSC_VER

proAddDress::proAddDress()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proAddDress::InitAsDefaultInstance() {
  dress_ = const_cast< ::cache::proDress*>(&::cache::proDress::default_instance());
}

proAddDress::proAddDress(const proAddDress& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proAddDress::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = 0u;
  dress_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proAddDress::~proAddDress() {
  SharedDtor();
}

void proAddDress::SharedDtor() {
  if (this != default_instance_) {
    delete dress_;
  }
}

void proAddDress::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proAddDress::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proAddDress_descriptor_;
}

const proAddDress& proAddDress::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proAddDress* proAddDress::default_instance_ = NULL;

proAddDress* proAddDress::New() const {
  return new proAddDress;
}

void proAddDress::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = 0u;
    if (has_dress()) {
      if (dress_ != NULL) dress_->::cache::proDress::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proAddDress::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_dress;
        break;
      }

      // required .cache.proDress dress = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dress:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dress()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proAddDress::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // required .cache.proDress dress = 2;
  if (has_dress()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->dress(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proAddDress::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // required .cache.proDress dress = 2;
  if (has_dress()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->dress(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proAddDress::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

    // required .cache.proDress dress = 2;
    if (has_dress()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dress());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proAddDress::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proAddDress* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proAddDress*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proAddDress::MergeFrom(const proAddDress& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_dress()) {
      mutable_dress()->::cache::proDress::MergeFrom(from.dress());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proAddDress::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proAddDress::CopyFrom(const proAddDress& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proAddDress::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_dress()) {
    if (!this->dress().IsInitialized()) return false;
  }
  return true;
}

void proAddDress::Swap(proAddDress* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(dress_, other->dress_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proAddDress::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proAddDress_descriptor_;
  metadata.reflection = proAddDress_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int proUpdateDress::kUserIdFieldNumber;
const int proUpdateDress::kDressFieldNumber;
#endif  // !_MSC_VER

proUpdateDress::proUpdateDress()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proUpdateDress::InitAsDefaultInstance() {
  dress_ = const_cast< ::cache::proDress*>(&::cache::proDress::default_instance());
}

proUpdateDress::proUpdateDress(const proUpdateDress& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proUpdateDress::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = 0u;
  dress_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proUpdateDress::~proUpdateDress() {
  SharedDtor();
}

void proUpdateDress::SharedDtor() {
  if (this != default_instance_) {
    delete dress_;
  }
}

void proUpdateDress::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proUpdateDress::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proUpdateDress_descriptor_;
}

const proUpdateDress& proUpdateDress::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proUpdateDress* proUpdateDress::default_instance_ = NULL;

proUpdateDress* proUpdateDress::New() const {
  return new proUpdateDress;
}

void proUpdateDress::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = 0u;
    if (has_dress()) {
      if (dress_ != NULL) dress_->::cache::proDress::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proUpdateDress::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_dress;
        break;
      }

      // required .cache.proDress dress = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dress:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dress()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proUpdateDress::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // required .cache.proDress dress = 2;
  if (has_dress()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->dress(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proUpdateDress::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // required .cache.proDress dress = 2;
  if (has_dress()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->dress(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proUpdateDress::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

    // required .cache.proDress dress = 2;
    if (has_dress()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dress());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proUpdateDress::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proUpdateDress* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proUpdateDress*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proUpdateDress::MergeFrom(const proUpdateDress& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_dress()) {
      mutable_dress()->::cache::proDress::MergeFrom(from.dress());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proUpdateDress::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proUpdateDress::CopyFrom(const proUpdateDress& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proUpdateDress::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_dress()) {
    if (!this->dress().IsInitialized()) return false;
  }
  return true;
}

void proUpdateDress::Swap(proUpdateDress* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(dress_, other->dress_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proUpdateDress::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proUpdateDress_descriptor_;
  metadata.reflection = proUpdateDress_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int proRemoveDress::kUserIdFieldNumber;
const int proRemoveDress::kDressIdFieldNumber;
#endif  // !_MSC_VER

proRemoveDress::proRemoveDress()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proRemoveDress::InitAsDefaultInstance() {
}

proRemoveDress::proRemoveDress(const proRemoveDress& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proRemoveDress::SharedCtor() {
  _cached_size_ = 0;
  user_id_ = 0u;
  dress_id_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proRemoveDress::~proRemoveDress() {
  SharedDtor();
}

void proRemoveDress::SharedDtor() {
  if (this != default_instance_) {
  }
}

void proRemoveDress::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proRemoveDress::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proRemoveDress_descriptor_;
}

const proRemoveDress& proRemoveDress::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proRemoveDress* proRemoveDress::default_instance_ = NULL;

proRemoveDress* proRemoveDress::New() const {
  return new proRemoveDress;
}

void proRemoveDress::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    user_id_ = 0u;
    dress_id_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proRemoveDress::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 user_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &user_id_)));
          set_has_user_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_dress_id;
        break;
      }

      // required uint32 dress_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_dress_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dress_id_)));
          set_has_dress_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proRemoveDress::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->user_id(), output);
  }

  // required uint32 dress_id = 2;
  if (has_dress_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->dress_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proRemoveDress::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 user_id = 1;
  if (has_user_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->user_id(), target);
  }

  // required uint32 dress_id = 2;
  if (has_dress_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->dress_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proRemoveDress::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 user_id = 1;
    if (has_user_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->user_id());
    }

    // required uint32 dress_id = 2;
    if (has_dress_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->dress_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proRemoveDress::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proRemoveDress* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proRemoveDress*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proRemoveDress::MergeFrom(const proRemoveDress& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_user_id()) {
      set_user_id(from.user_id());
    }
    if (from.has_dress_id()) {
      set_dress_id(from.dress_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proRemoveDress::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proRemoveDress::CopyFrom(const proRemoveDress& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proRemoveDress::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void proRemoveDress::Swap(proRemoveDress* other) {
  if (other != this) {
    std::swap(user_id_, other->user_id_);
    std::swap(dress_id_, other->dress_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proRemoveDress::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proRemoveDress_descriptor_;
  metadata.reflection = proRemoveDress_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int proDressRes::kCodeFieldNumber;
const int proDressRes::kDressFieldNumber;
#endif  // !_MSC_VER

proDressRes::proDressRes()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proDressRes::InitAsDefaultInstance() {
  dress_ = const_cast< ::cache::proDress*>(&::cache::proDress::default_instance());
}

proDressRes::proDressRes(const proDressRes& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proDressRes::SharedCtor() {
  _cached_size_ = 0;
  code_ = 0u;
  dress_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proDressRes::~proDressRes() {
  SharedDtor();
}

void proDressRes::SharedDtor() {
  if (this != default_instance_) {
    delete dress_;
  }
}

void proDressRes::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proDressRes::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proDressRes_descriptor_;
}

const proDressRes& proDressRes::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proDressRes* proDressRes::default_instance_ = NULL;

proDressRes* proDressRes::New() const {
  return new proDressRes;
}

void proDressRes::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    code_ = 0u;
    if (has_dress()) {
      if (dress_ != NULL) dress_->::cache::proDress::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proDressRes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &code_)));
          set_has_code();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_dress;
        break;
      }

      // optional .cache.proDress dress = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dress:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dress()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proDressRes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 code = 1;
  if (has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->code(), output);
  }

  // optional .cache.proDress dress = 2;
  if (has_dress()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->dress(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proDressRes::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 code = 1;
  if (has_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->code(), target);
  }

  // optional .cache.proDress dress = 2;
  if (has_dress()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->dress(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proDressRes::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 code = 1;
    if (has_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->code());
    }

    // optional .cache.proDress dress = 2;
    if (has_dress()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dress());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proDressRes::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proDressRes* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proDressRes*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proDressRes::MergeFrom(const proDressRes& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_code()) {
      set_code(from.code());
    }
    if (from.has_dress()) {
      mutable_dress()->::cache::proDress::MergeFrom(from.dress());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proDressRes::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proDressRes::CopyFrom(const proDressRes& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proDressRes::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_dress()) {
    if (!this->dress().IsInitialized()) return false;
  }
  return true;
}

void proDressRes::Swap(proDressRes* other) {
  if (other != this) {
    std::swap(code_, other->code_);
    std::swap(dress_, other->dress_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proDressRes::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proDressRes_descriptor_;
  metadata.reflection = proDressRes_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int proDressesRes::kCodeFieldNumber;
const int proDressesRes::kDressesFieldNumber;
#endif  // !_MSC_VER

proDressesRes::proDressesRes()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void proDressesRes::InitAsDefaultInstance() {
}

proDressesRes::proDressesRes(const proDressesRes& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void proDressesRes::SharedCtor() {
  _cached_size_ = 0;
  code_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

proDressesRes::~proDressesRes() {
  SharedDtor();
}

void proDressesRes::SharedDtor() {
  if (this != default_instance_) {
  }
}

void proDressesRes::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* proDressesRes::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return proDressesRes_descriptor_;
}

const proDressesRes& proDressesRes::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dress_2eproto();
  return *default_instance_;
}

proDressesRes* proDressesRes::default_instance_ = NULL;

proDressesRes* proDressesRes::New() const {
  return new proDressesRes;
}

void proDressesRes::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    code_ = 0u;
  }
  dresses_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool proDressesRes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &code_)));
          set_has_code();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_dresses;
        break;
      }

      // repeated .cache.proDress dresses = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_dresses:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_dresses()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_dresses;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void proDressesRes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 code = 1;
  if (has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->code(), output);
  }

  // repeated .cache.proDress dresses = 2;
  for (int i = 0; i < this->dresses_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->dresses(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* proDressesRes::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 code = 1;
  if (has_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->code(), target);
  }

  // repeated .cache.proDress dresses = 2;
  for (int i = 0; i < this->dresses_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->dresses(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int proDressesRes::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 code = 1;
    if (has_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->code());
    }

  }
  // repeated .cache.proDress dresses = 2;
  total_size += 1 * this->dresses_size();
  for (int i = 0; i < this->dresses_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->dresses(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void proDressesRes::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const proDressesRes* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const proDressesRes*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void proDressesRes::MergeFrom(const proDressesRes& from) {
  GOOGLE_CHECK_NE(&from, this);
  dresses_.MergeFrom(from.dresses_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_code()) {
      set_code(from.code());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void proDressesRes::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void proDressesRes::CopyFrom(const proDressesRes& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool proDressesRes::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < dresses_size(); i++) {
    if (!this->dresses(i).IsInitialized()) return false;
  }
  return true;
}

void proDressesRes::Swap(proDressesRes* other) {
  if (other != this) {
    std::swap(code_, other->code_);
    dresses_.Swap(&other->dresses_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata proDressesRes::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = proDressesRes_descriptor_;
  metadata.reflection = proDressesRes_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cache

// @@protoc_insertion_point(global_scope)
