// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: equip.proto

#ifndef PROTOBUF_equip_2eproto__INCLUDED
#define PROTOBUF_equip_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cache {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_equip_2eproto();
void protobuf_AssignDesc_equip_2eproto();
void protobuf_ShutdownFile_equip_2eproto();

class proEquip;
class proGetEquip;
class proGetEquips;
class proGetEquipsByPos;
class proAddEquip;
class proAddEquips;
class proUpdateEquip;
class proUpdateEquips;
class proRemoveEquip;
class proRemoveEquips;
class proEquipRes;
class proEquipsRes;

// ===================================================================

class proEquip : public ::google::protobuf::Message {
 public:
  proEquip();
  virtual ~proEquip();

  proEquip(const proEquip& from);

  inline proEquip& operator=(const proEquip& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proEquip& default_instance();

  void Swap(proEquip* other);

  // implements Message ----------------------------------------------

  proEquip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proEquip& from);
  void MergeFrom(const proEquip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // required uint32 sid = 2;
  inline bool has_sid() const;
  inline void clear_sid();
  static const int kSidFieldNumber = 2;
  inline ::google::protobuf::uint32 sid() const;
  inline void set_sid(::google::protobuf::uint32 value);

  // required uint32 exp = 3;
  inline bool has_exp() const;
  inline void clear_exp();
  static const int kExpFieldNumber = 3;
  inline ::google::protobuf::uint32 exp() const;
  inline void set_exp(::google::protobuf::uint32 value);

  // required uint32 level = 4;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 4;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);

  // required uint32 gem = 5;
  inline bool has_gem() const;
  inline void clear_gem();
  static const int kGemFieldNumber = 5;
  inline ::google::protobuf::uint32 gem() const;
  inline void set_gem(::google::protobuf::uint32 value);

  // required uint32 pos = 6;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 6;
  inline ::google::protobuf::uint32 pos() const;
  inline void set_pos(::google::protobuf::uint32 value);

  // required uint32 type = 7;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 7;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // required uint32 color = 8;
  inline bool has_color() const;
  inline void clear_color();
  static const int kColorFieldNumber = 8;
  inline ::google::protobuf::uint32 color() const;
  inline void set_color(::google::protobuf::uint32 value);

  // required uint32 refining = 9;
  inline bool has_refining() const;
  inline void clear_refining();
  static const int kRefiningFieldNumber = 9;
  inline ::google::protobuf::uint32 refining() const;
  inline void set_refining(::google::protobuf::uint32 value);

  // required uint32 refining_exp = 10;
  inline bool has_refining_exp() const;
  inline void clear_refining_exp();
  static const int kRefiningExpFieldNumber = 10;
  inline ::google::protobuf::uint32 refining_exp() const;
  inline void set_refining_exp(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cache.proEquip)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_sid();
  inline void clear_has_sid();
  inline void set_has_exp();
  inline void clear_has_exp();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_gem();
  inline void clear_has_gem();
  inline void set_has_pos();
  inline void clear_has_pos();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_color();
  inline void clear_has_color();
  inline void set_has_refining();
  inline void clear_has_refining();
  inline void set_has_refining_exp();
  inline void clear_has_refining_exp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint32 sid_;
  ::google::protobuf::uint32 exp_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 gem_;
  ::google::protobuf::uint32 pos_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 color_;
  ::google::protobuf::uint32 refining_;
  ::google::protobuf::uint32 refining_exp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proEquip* default_instance_;
};
// -------------------------------------------------------------------

class proGetEquip : public ::google::protobuf::Message {
 public:
  proGetEquip();
  virtual ~proGetEquip();

  proGetEquip(const proGetEquip& from);

  inline proGetEquip& operator=(const proGetEquip& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proGetEquip& default_instance();

  void Swap(proGetEquip* other);

  // implements Message ----------------------------------------------

  proGetEquip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proGetEquip& from);
  void MergeFrom(const proGetEquip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required uint64 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:cache.proGetEquip)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proGetEquip* default_instance_;
};
// -------------------------------------------------------------------

class proGetEquips : public ::google::protobuf::Message {
 public:
  proGetEquips();
  virtual ~proGetEquips();

  proGetEquips(const proGetEquips& from);

  inline proGetEquips& operator=(const proGetEquips& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proGetEquips& default_instance();

  void Swap(proGetEquips* other);

  // implements Message ----------------------------------------------

  proGetEquips* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proGetEquips& from);
  void MergeFrom(const proGetEquips& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cache.proGetEquips)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proGetEquips* default_instance_;
};
// -------------------------------------------------------------------

class proGetEquipsByPos : public ::google::protobuf::Message {
 public:
  proGetEquipsByPos();
  virtual ~proGetEquipsByPos();

  proGetEquipsByPos(const proGetEquipsByPos& from);

  inline proGetEquipsByPos& operator=(const proGetEquipsByPos& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proGetEquipsByPos& default_instance();

  void Swap(proGetEquipsByPos* other);

  // implements Message ----------------------------------------------

  proGetEquipsByPos* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proGetEquipsByPos& from);
  void MergeFrom(const proGetEquipsByPos& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated uint32 pos_list = 2;
  inline int pos_list_size() const;
  inline void clear_pos_list();
  static const int kPosListFieldNumber = 2;
  inline ::google::protobuf::uint32 pos_list(int index) const;
  inline void set_pos_list(int index, ::google::protobuf::uint32 value);
  inline void add_pos_list(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      pos_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_pos_list();

  // @@protoc_insertion_point(class_scope:cache.proGetEquipsByPos)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > pos_list_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proGetEquipsByPos* default_instance_;
};
// -------------------------------------------------------------------

class proAddEquip : public ::google::protobuf::Message {
 public:
  proAddEquip();
  virtual ~proAddEquip();

  proAddEquip(const proAddEquip& from);

  inline proAddEquip& operator=(const proAddEquip& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proAddEquip& default_instance();

  void Swap(proAddEquip* other);

  // implements Message ----------------------------------------------

  proAddEquip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proAddEquip& from);
  void MergeFrom(const proAddEquip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required .cache.proEquip equip = 2;
  inline bool has_equip() const;
  inline void clear_equip();
  static const int kEquipFieldNumber = 2;
  inline const ::cache::proEquip& equip() const;
  inline ::cache::proEquip* mutable_equip();
  inline ::cache::proEquip* release_equip();
  inline void set_allocated_equip(::cache::proEquip* equip);

  // @@protoc_insertion_point(class_scope:cache.proAddEquip)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_equip();
  inline void clear_has_equip();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proEquip* equip_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proAddEquip* default_instance_;
};
// -------------------------------------------------------------------

class proAddEquips : public ::google::protobuf::Message {
 public:
  proAddEquips();
  virtual ~proAddEquips();

  proAddEquips(const proAddEquips& from);

  inline proAddEquips& operator=(const proAddEquips& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proAddEquips& default_instance();

  void Swap(proAddEquips* other);

  // implements Message ----------------------------------------------

  proAddEquips* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proAddEquips& from);
  void MergeFrom(const proAddEquips& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated .cache.proEquip equips = 2;
  inline int equips_size() const;
  inline void clear_equips();
  static const int kEquipsFieldNumber = 2;
  inline const ::cache::proEquip& equips(int index) const;
  inline ::cache::proEquip* mutable_equips(int index);
  inline ::cache::proEquip* add_equips();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proEquip >&
      equips() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proEquip >*
      mutable_equips();

  // @@protoc_insertion_point(class_scope:cache.proAddEquips)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proEquip > equips_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proAddEquips* default_instance_;
};
// -------------------------------------------------------------------

class proUpdateEquip : public ::google::protobuf::Message {
 public:
  proUpdateEquip();
  virtual ~proUpdateEquip();

  proUpdateEquip(const proUpdateEquip& from);

  inline proUpdateEquip& operator=(const proUpdateEquip& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proUpdateEquip& default_instance();

  void Swap(proUpdateEquip* other);

  // implements Message ----------------------------------------------

  proUpdateEquip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proUpdateEquip& from);
  void MergeFrom(const proUpdateEquip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required .cache.proEquip equip = 2;
  inline bool has_equip() const;
  inline void clear_equip();
  static const int kEquipFieldNumber = 2;
  inline const ::cache::proEquip& equip() const;
  inline ::cache::proEquip* mutable_equip();
  inline ::cache::proEquip* release_equip();
  inline void set_allocated_equip(::cache::proEquip* equip);

  // @@protoc_insertion_point(class_scope:cache.proUpdateEquip)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_equip();
  inline void clear_has_equip();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proEquip* equip_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proUpdateEquip* default_instance_;
};
// -------------------------------------------------------------------

class proUpdateEquips : public ::google::protobuf::Message {
 public:
  proUpdateEquips();
  virtual ~proUpdateEquips();

  proUpdateEquips(const proUpdateEquips& from);

  inline proUpdateEquips& operator=(const proUpdateEquips& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proUpdateEquips& default_instance();

  void Swap(proUpdateEquips* other);

  // implements Message ----------------------------------------------

  proUpdateEquips* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proUpdateEquips& from);
  void MergeFrom(const proUpdateEquips& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated .cache.proEquip equips = 2;
  inline int equips_size() const;
  inline void clear_equips();
  static const int kEquipsFieldNumber = 2;
  inline const ::cache::proEquip& equips(int index) const;
  inline ::cache::proEquip* mutable_equips(int index);
  inline ::cache::proEquip* add_equips();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proEquip >&
      equips() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proEquip >*
      mutable_equips();

  // @@protoc_insertion_point(class_scope:cache.proUpdateEquips)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proEquip > equips_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proUpdateEquips* default_instance_;
};
// -------------------------------------------------------------------

class proRemoveEquip : public ::google::protobuf::Message {
 public:
  proRemoveEquip();
  virtual ~proRemoveEquip();

  proRemoveEquip(const proRemoveEquip& from);

  inline proRemoveEquip& operator=(const proRemoveEquip& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proRemoveEquip& default_instance();

  void Swap(proRemoveEquip* other);

  // implements Message ----------------------------------------------

  proRemoveEquip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proRemoveEquip& from);
  void MergeFrom(const proRemoveEquip& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required uint64 equip_id = 2;
  inline bool has_equip_id() const;
  inline void clear_equip_id();
  static const int kEquipIdFieldNumber = 2;
  inline ::google::protobuf::uint64 equip_id() const;
  inline void set_equip_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:cache.proRemoveEquip)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_equip_id();
  inline void clear_has_equip_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 equip_id_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proRemoveEquip* default_instance_;
};
// -------------------------------------------------------------------

class proRemoveEquips : public ::google::protobuf::Message {
 public:
  proRemoveEquips();
  virtual ~proRemoveEquips();

  proRemoveEquips(const proRemoveEquips& from);

  inline proRemoveEquips& operator=(const proRemoveEquips& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proRemoveEquips& default_instance();

  void Swap(proRemoveEquips* other);

  // implements Message ----------------------------------------------

  proRemoveEquips* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proRemoveEquips& from);
  void MergeFrom(const proRemoveEquips& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated uint64 equip_ids = 2;
  inline int equip_ids_size() const;
  inline void clear_equip_ids();
  static const int kEquipIdsFieldNumber = 2;
  inline ::google::protobuf::uint64 equip_ids(int index) const;
  inline void set_equip_ids(int index, ::google::protobuf::uint64 value);
  inline void add_equip_ids(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      equip_ids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_equip_ids();

  // @@protoc_insertion_point(class_scope:cache.proRemoveEquips)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > equip_ids_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proRemoveEquips* default_instance_;
};
// -------------------------------------------------------------------

class proEquipRes : public ::google::protobuf::Message {
 public:
  proEquipRes();
  virtual ~proEquipRes();

  proEquipRes(const proEquipRes& from);

  inline proEquipRes& operator=(const proEquipRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proEquipRes& default_instance();

  void Swap(proEquipRes* other);

  // implements Message ----------------------------------------------

  proEquipRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proEquipRes& from);
  void MergeFrom(const proEquipRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 code() const;
  inline void set_code(::google::protobuf::uint32 value);

  // optional .cache.proEquip equip = 2;
  inline bool has_equip() const;
  inline void clear_equip();
  static const int kEquipFieldNumber = 2;
  inline const ::cache::proEquip& equip() const;
  inline ::cache::proEquip* mutable_equip();
  inline ::cache::proEquip* release_equip();
  inline void set_allocated_equip(::cache::proEquip* equip);

  // @@protoc_insertion_point(class_scope:cache.proEquipRes)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_equip();
  inline void clear_has_equip();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proEquip* equip_;
  ::google::protobuf::uint32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proEquipRes* default_instance_;
};
// -------------------------------------------------------------------

class proEquipsRes : public ::google::protobuf::Message {
 public:
  proEquipsRes();
  virtual ~proEquipsRes();

  proEquipsRes(const proEquipsRes& from);

  inline proEquipsRes& operator=(const proEquipsRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proEquipsRes& default_instance();

  void Swap(proEquipsRes* other);

  // implements Message ----------------------------------------------

  proEquipsRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proEquipsRes& from);
  void MergeFrom(const proEquipsRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 code() const;
  inline void set_code(::google::protobuf::uint32 value);

  // repeated .cache.proEquip equips = 2;
  inline int equips_size() const;
  inline void clear_equips();
  static const int kEquipsFieldNumber = 2;
  inline const ::cache::proEquip& equips(int index) const;
  inline ::cache::proEquip* mutable_equips(int index);
  inline ::cache::proEquip* add_equips();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proEquip >&
      equips() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proEquip >*
      mutable_equips();

  // @@protoc_insertion_point(class_scope:cache.proEquipsRes)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proEquip > equips_;
  ::google::protobuf::uint32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_equip_2eproto();
  friend void protobuf_AssignDesc_equip_2eproto();
  friend void protobuf_ShutdownFile_equip_2eproto();

  void InitAsDefaultInstance();
  static proEquipsRes* default_instance_;
};
// ===================================================================


// ===================================================================

// proEquip

// required uint64 id = 1;
inline bool proEquip::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proEquip::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proEquip::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proEquip::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 proEquip::id() const {
  return id_;
}
inline void proEquip::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
}

// required uint32 sid = 2;
inline bool proEquip::has_sid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proEquip::set_has_sid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proEquip::clear_has_sid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proEquip::clear_sid() {
  sid_ = 0u;
  clear_has_sid();
}
inline ::google::protobuf::uint32 proEquip::sid() const {
  return sid_;
}
inline void proEquip::set_sid(::google::protobuf::uint32 value) {
  set_has_sid();
  sid_ = value;
}

// required uint32 exp = 3;
inline bool proEquip::has_exp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void proEquip::set_has_exp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void proEquip::clear_has_exp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void proEquip::clear_exp() {
  exp_ = 0u;
  clear_has_exp();
}
inline ::google::protobuf::uint32 proEquip::exp() const {
  return exp_;
}
inline void proEquip::set_exp(::google::protobuf::uint32 value) {
  set_has_exp();
  exp_ = value;
}

// required uint32 level = 4;
inline bool proEquip::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void proEquip::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void proEquip::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void proEquip::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 proEquip::level() const {
  return level_;
}
inline void proEquip::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
}

// required uint32 gem = 5;
inline bool proEquip::has_gem() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void proEquip::set_has_gem() {
  _has_bits_[0] |= 0x00000010u;
}
inline void proEquip::clear_has_gem() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void proEquip::clear_gem() {
  gem_ = 0u;
  clear_has_gem();
}
inline ::google::protobuf::uint32 proEquip::gem() const {
  return gem_;
}
inline void proEquip::set_gem(::google::protobuf::uint32 value) {
  set_has_gem();
  gem_ = value;
}

// required uint32 pos = 6;
inline bool proEquip::has_pos() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void proEquip::set_has_pos() {
  _has_bits_[0] |= 0x00000020u;
}
inline void proEquip::clear_has_pos() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void proEquip::clear_pos() {
  pos_ = 0u;
  clear_has_pos();
}
inline ::google::protobuf::uint32 proEquip::pos() const {
  return pos_;
}
inline void proEquip::set_pos(::google::protobuf::uint32 value) {
  set_has_pos();
  pos_ = value;
}

// required uint32 type = 7;
inline bool proEquip::has_type() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void proEquip::set_has_type() {
  _has_bits_[0] |= 0x00000040u;
}
inline void proEquip::clear_has_type() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void proEquip::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 proEquip::type() const {
  return type_;
}
inline void proEquip::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
}

// required uint32 color = 8;
inline bool proEquip::has_color() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void proEquip::set_has_color() {
  _has_bits_[0] |= 0x00000080u;
}
inline void proEquip::clear_has_color() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void proEquip::clear_color() {
  color_ = 0u;
  clear_has_color();
}
inline ::google::protobuf::uint32 proEquip::color() const {
  return color_;
}
inline void proEquip::set_color(::google::protobuf::uint32 value) {
  set_has_color();
  color_ = value;
}

// required uint32 refining = 9;
inline bool proEquip::has_refining() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void proEquip::set_has_refining() {
  _has_bits_[0] |= 0x00000100u;
}
inline void proEquip::clear_has_refining() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void proEquip::clear_refining() {
  refining_ = 0u;
  clear_has_refining();
}
inline ::google::protobuf::uint32 proEquip::refining() const {
  return refining_;
}
inline void proEquip::set_refining(::google::protobuf::uint32 value) {
  set_has_refining();
  refining_ = value;
}

// required uint32 refining_exp = 10;
inline bool proEquip::has_refining_exp() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void proEquip::set_has_refining_exp() {
  _has_bits_[0] |= 0x00000200u;
}
inline void proEquip::clear_has_refining_exp() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void proEquip::clear_refining_exp() {
  refining_exp_ = 0u;
  clear_has_refining_exp();
}
inline ::google::protobuf::uint32 proEquip::refining_exp() const {
  return refining_exp_;
}
inline void proEquip::set_refining_exp(::google::protobuf::uint32 value) {
  set_has_refining_exp();
  refining_exp_ = value;
}

// -------------------------------------------------------------------

// proGetEquip

// required uint32 user_id = 1;
inline bool proGetEquip::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proGetEquip::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proGetEquip::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proGetEquip::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proGetEquip::user_id() const {
  return user_id_;
}
inline void proGetEquip::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required uint64 id = 2;
inline bool proGetEquip::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proGetEquip::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proGetEquip::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proGetEquip::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 proGetEquip::id() const {
  return id_;
}
inline void proGetEquip::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// proGetEquips

// required uint32 user_id = 1;
inline bool proGetEquips::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proGetEquips::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proGetEquips::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proGetEquips::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proGetEquips::user_id() const {
  return user_id_;
}
inline void proGetEquips::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// -------------------------------------------------------------------

// proGetEquipsByPos

// required uint32 user_id = 1;
inline bool proGetEquipsByPos::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proGetEquipsByPos::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proGetEquipsByPos::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proGetEquipsByPos::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proGetEquipsByPos::user_id() const {
  return user_id_;
}
inline void proGetEquipsByPos::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated uint32 pos_list = 2;
inline int proGetEquipsByPos::pos_list_size() const {
  return pos_list_.size();
}
inline void proGetEquipsByPos::clear_pos_list() {
  pos_list_.Clear();
}
inline ::google::protobuf::uint32 proGetEquipsByPos::pos_list(int index) const {
  return pos_list_.Get(index);
}
inline void proGetEquipsByPos::set_pos_list(int index, ::google::protobuf::uint32 value) {
  pos_list_.Set(index, value);
}
inline void proGetEquipsByPos::add_pos_list(::google::protobuf::uint32 value) {
  pos_list_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
proGetEquipsByPos::pos_list() const {
  return pos_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
proGetEquipsByPos::mutable_pos_list() {
  return &pos_list_;
}

// -------------------------------------------------------------------

// proAddEquip

// required uint32 user_id = 1;
inline bool proAddEquip::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proAddEquip::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proAddEquip::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proAddEquip::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proAddEquip::user_id() const {
  return user_id_;
}
inline void proAddEquip::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required .cache.proEquip equip = 2;
inline bool proAddEquip::has_equip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proAddEquip::set_has_equip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proAddEquip::clear_has_equip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proAddEquip::clear_equip() {
  if (equip_ != NULL) equip_->::cache::proEquip::Clear();
  clear_has_equip();
}
inline const ::cache::proEquip& proAddEquip::equip() const {
  return equip_ != NULL ? *equip_ : *default_instance_->equip_;
}
inline ::cache::proEquip* proAddEquip::mutable_equip() {
  set_has_equip();
  if (equip_ == NULL) equip_ = new ::cache::proEquip;
  return equip_;
}
inline ::cache::proEquip* proAddEquip::release_equip() {
  clear_has_equip();
  ::cache::proEquip* temp = equip_;
  equip_ = NULL;
  return temp;
}
inline void proAddEquip::set_allocated_equip(::cache::proEquip* equip) {
  delete equip_;
  equip_ = equip;
  if (equip) {
    set_has_equip();
  } else {
    clear_has_equip();
  }
}

// -------------------------------------------------------------------

// proAddEquips

// required uint32 user_id = 1;
inline bool proAddEquips::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proAddEquips::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proAddEquips::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proAddEquips::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proAddEquips::user_id() const {
  return user_id_;
}
inline void proAddEquips::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .cache.proEquip equips = 2;
inline int proAddEquips::equips_size() const {
  return equips_.size();
}
inline void proAddEquips::clear_equips() {
  equips_.Clear();
}
inline const ::cache::proEquip& proAddEquips::equips(int index) const {
  return equips_.Get(index);
}
inline ::cache::proEquip* proAddEquips::mutable_equips(int index) {
  return equips_.Mutable(index);
}
inline ::cache::proEquip* proAddEquips::add_equips() {
  return equips_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proEquip >&
proAddEquips::equips() const {
  return equips_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proEquip >*
proAddEquips::mutable_equips() {
  return &equips_;
}

// -------------------------------------------------------------------

// proUpdateEquip

// required uint32 user_id = 1;
inline bool proUpdateEquip::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proUpdateEquip::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proUpdateEquip::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proUpdateEquip::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proUpdateEquip::user_id() const {
  return user_id_;
}
inline void proUpdateEquip::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required .cache.proEquip equip = 2;
inline bool proUpdateEquip::has_equip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proUpdateEquip::set_has_equip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proUpdateEquip::clear_has_equip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proUpdateEquip::clear_equip() {
  if (equip_ != NULL) equip_->::cache::proEquip::Clear();
  clear_has_equip();
}
inline const ::cache::proEquip& proUpdateEquip::equip() const {
  return equip_ != NULL ? *equip_ : *default_instance_->equip_;
}
inline ::cache::proEquip* proUpdateEquip::mutable_equip() {
  set_has_equip();
  if (equip_ == NULL) equip_ = new ::cache::proEquip;
  return equip_;
}
inline ::cache::proEquip* proUpdateEquip::release_equip() {
  clear_has_equip();
  ::cache::proEquip* temp = equip_;
  equip_ = NULL;
  return temp;
}
inline void proUpdateEquip::set_allocated_equip(::cache::proEquip* equip) {
  delete equip_;
  equip_ = equip;
  if (equip) {
    set_has_equip();
  } else {
    clear_has_equip();
  }
}

// -------------------------------------------------------------------

// proUpdateEquips

// required uint32 user_id = 1;
inline bool proUpdateEquips::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proUpdateEquips::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proUpdateEquips::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proUpdateEquips::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proUpdateEquips::user_id() const {
  return user_id_;
}
inline void proUpdateEquips::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .cache.proEquip equips = 2;
inline int proUpdateEquips::equips_size() const {
  return equips_.size();
}
inline void proUpdateEquips::clear_equips() {
  equips_.Clear();
}
inline const ::cache::proEquip& proUpdateEquips::equips(int index) const {
  return equips_.Get(index);
}
inline ::cache::proEquip* proUpdateEquips::mutable_equips(int index) {
  return equips_.Mutable(index);
}
inline ::cache::proEquip* proUpdateEquips::add_equips() {
  return equips_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proEquip >&
proUpdateEquips::equips() const {
  return equips_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proEquip >*
proUpdateEquips::mutable_equips() {
  return &equips_;
}

// -------------------------------------------------------------------

// proRemoveEquip

// required uint32 user_id = 1;
inline bool proRemoveEquip::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proRemoveEquip::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proRemoveEquip::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proRemoveEquip::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proRemoveEquip::user_id() const {
  return user_id_;
}
inline void proRemoveEquip::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required uint64 equip_id = 2;
inline bool proRemoveEquip::has_equip_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proRemoveEquip::set_has_equip_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proRemoveEquip::clear_has_equip_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proRemoveEquip::clear_equip_id() {
  equip_id_ = GOOGLE_ULONGLONG(0);
  clear_has_equip_id();
}
inline ::google::protobuf::uint64 proRemoveEquip::equip_id() const {
  return equip_id_;
}
inline void proRemoveEquip::set_equip_id(::google::protobuf::uint64 value) {
  set_has_equip_id();
  equip_id_ = value;
}

// -------------------------------------------------------------------

// proRemoveEquips

// required uint32 user_id = 1;
inline bool proRemoveEquips::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proRemoveEquips::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proRemoveEquips::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proRemoveEquips::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proRemoveEquips::user_id() const {
  return user_id_;
}
inline void proRemoveEquips::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated uint64 equip_ids = 2;
inline int proRemoveEquips::equip_ids_size() const {
  return equip_ids_.size();
}
inline void proRemoveEquips::clear_equip_ids() {
  equip_ids_.Clear();
}
inline ::google::protobuf::uint64 proRemoveEquips::equip_ids(int index) const {
  return equip_ids_.Get(index);
}
inline void proRemoveEquips::set_equip_ids(int index, ::google::protobuf::uint64 value) {
  equip_ids_.Set(index, value);
}
inline void proRemoveEquips::add_equip_ids(::google::protobuf::uint64 value) {
  equip_ids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
proRemoveEquips::equip_ids() const {
  return equip_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
proRemoveEquips::mutable_equip_ids() {
  return &equip_ids_;
}

// -------------------------------------------------------------------

// proEquipRes

// required uint32 code = 1;
inline bool proEquipRes::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proEquipRes::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proEquipRes::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proEquipRes::clear_code() {
  code_ = 0u;
  clear_has_code();
}
inline ::google::protobuf::uint32 proEquipRes::code() const {
  return code_;
}
inline void proEquipRes::set_code(::google::protobuf::uint32 value) {
  set_has_code();
  code_ = value;
}

// optional .cache.proEquip equip = 2;
inline bool proEquipRes::has_equip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proEquipRes::set_has_equip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proEquipRes::clear_has_equip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proEquipRes::clear_equip() {
  if (equip_ != NULL) equip_->::cache::proEquip::Clear();
  clear_has_equip();
}
inline const ::cache::proEquip& proEquipRes::equip() const {
  return equip_ != NULL ? *equip_ : *default_instance_->equip_;
}
inline ::cache::proEquip* proEquipRes::mutable_equip() {
  set_has_equip();
  if (equip_ == NULL) equip_ = new ::cache::proEquip;
  return equip_;
}
inline ::cache::proEquip* proEquipRes::release_equip() {
  clear_has_equip();
  ::cache::proEquip* temp = equip_;
  equip_ = NULL;
  return temp;
}
inline void proEquipRes::set_allocated_equip(::cache::proEquip* equip) {
  delete equip_;
  equip_ = equip;
  if (equip) {
    set_has_equip();
  } else {
    clear_has_equip();
  }
}

// -------------------------------------------------------------------

// proEquipsRes

// required uint32 code = 1;
inline bool proEquipsRes::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proEquipsRes::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proEquipsRes::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proEquipsRes::clear_code() {
  code_ = 0u;
  clear_has_code();
}
inline ::google::protobuf::uint32 proEquipsRes::code() const {
  return code_;
}
inline void proEquipsRes::set_code(::google::protobuf::uint32 value) {
  set_has_code();
  code_ = value;
}

// repeated .cache.proEquip equips = 2;
inline int proEquipsRes::equips_size() const {
  return equips_.size();
}
inline void proEquipsRes::clear_equips() {
  equips_.Clear();
}
inline const ::cache::proEquip& proEquipsRes::equips(int index) const {
  return equips_.Get(index);
}
inline ::cache::proEquip* proEquipsRes::mutable_equips(int index) {
  return equips_.Mutable(index);
}
inline ::cache::proEquip* proEquipsRes::add_equips() {
  return equips_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proEquip >&
proEquipsRes::equips() const {
  return equips_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proEquip >*
proEquipsRes::mutable_equips() {
  return &equips_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cache

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_equip_2eproto__INCLUDED
