// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: item.proto

#ifndef PROTOBUF_item_2eproto__INCLUDED
#define PROTOBUF_item_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cache {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_item_2eproto();
void protobuf_AssignDesc_item_2eproto();
void protobuf_ShutdownFile_item_2eproto();

class proItem;
class proGetItem;
class proGetItems;
class proAddItem;
class proAddItems;
class proRemoveItem;
class proRemoveItems;
class proItemRes;
class proItemsRes;

// ===================================================================

class proItem : public ::google::protobuf::Message {
 public:
  proItem();
  virtual ~proItem();

  proItem(const proItem& from);

  inline proItem& operator=(const proItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proItem& default_instance();

  void Swap(proItem* other);

  // implements Message ----------------------------------------------

  proItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proItem& from);
  void MergeFrom(const proItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 item_id = 1;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 1;
  inline ::google::protobuf::uint32 item_id() const;
  inline void set_item_id(::google::protobuf::uint32 value);

  // required uint32 num = 2;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 2;
  inline ::google::protobuf::uint32 num() const;
  inline void set_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cache.proItem)
 private:
  inline void set_has_item_id();
  inline void clear_has_item_id();
  inline void set_has_num();
  inline void clear_has_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 item_id_;
  ::google::protobuf::uint32 num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proItem* default_instance_;
};
// -------------------------------------------------------------------

class proGetItem : public ::google::protobuf::Message {
 public:
  proGetItem();
  virtual ~proGetItem();

  proGetItem(const proGetItem& from);

  inline proGetItem& operator=(const proGetItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proGetItem& default_instance();

  void Swap(proGetItem* other);

  // implements Message ----------------------------------------------

  proGetItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proGetItem& from);
  void MergeFrom(const proGetItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required uint32 item_id = 2;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 2;
  inline ::google::protobuf::uint32 item_id() const;
  inline void set_item_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cache.proGetItem)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_item_id();
  inline void clear_has_item_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 user_id_;
  ::google::protobuf::uint32 item_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proGetItem* default_instance_;
};
// -------------------------------------------------------------------

class proGetItems : public ::google::protobuf::Message {
 public:
  proGetItems();
  virtual ~proGetItems();

  proGetItems(const proGetItems& from);

  inline proGetItems& operator=(const proGetItems& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proGetItems& default_instance();

  void Swap(proGetItems* other);

  // implements Message ----------------------------------------------

  proGetItems* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proGetItems& from);
  void MergeFrom(const proGetItems& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cache.proGetItems)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proGetItems* default_instance_;
};
// -------------------------------------------------------------------

class proAddItem : public ::google::protobuf::Message {
 public:
  proAddItem();
  virtual ~proAddItem();

  proAddItem(const proAddItem& from);

  inline proAddItem& operator=(const proAddItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proAddItem& default_instance();

  void Swap(proAddItem* other);

  // implements Message ----------------------------------------------

  proAddItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proAddItem& from);
  void MergeFrom(const proAddItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required .cache.proItem item = 2;
  inline bool has_item() const;
  inline void clear_item();
  static const int kItemFieldNumber = 2;
  inline const ::cache::proItem& item() const;
  inline ::cache::proItem* mutable_item();
  inline ::cache::proItem* release_item();
  inline void set_allocated_item(::cache::proItem* item);

  // @@protoc_insertion_point(class_scope:cache.proAddItem)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_item();
  inline void clear_has_item();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proItem* item_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proAddItem* default_instance_;
};
// -------------------------------------------------------------------

class proAddItems : public ::google::protobuf::Message {
 public:
  proAddItems();
  virtual ~proAddItems();

  proAddItems(const proAddItems& from);

  inline proAddItems& operator=(const proAddItems& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proAddItems& default_instance();

  void Swap(proAddItems* other);

  // implements Message ----------------------------------------------

  proAddItems* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proAddItems& from);
  void MergeFrom(const proAddItems& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated .cache.proItem items = 2;
  inline int items_size() const;
  inline void clear_items();
  static const int kItemsFieldNumber = 2;
  inline const ::cache::proItem& items(int index) const;
  inline ::cache::proItem* mutable_items(int index);
  inline ::cache::proItem* add_items();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proItem >&
      items() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proItem >*
      mutable_items();

  // @@protoc_insertion_point(class_scope:cache.proAddItems)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proItem > items_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proAddItems* default_instance_;
};
// -------------------------------------------------------------------

class proRemoveItem : public ::google::protobuf::Message {
 public:
  proRemoveItem();
  virtual ~proRemoveItem();

  proRemoveItem(const proRemoveItem& from);

  inline proRemoveItem& operator=(const proRemoveItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proRemoveItem& default_instance();

  void Swap(proRemoveItem* other);

  // implements Message ----------------------------------------------

  proRemoveItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proRemoveItem& from);
  void MergeFrom(const proRemoveItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required .cache.proItem item = 2;
  inline bool has_item() const;
  inline void clear_item();
  static const int kItemFieldNumber = 2;
  inline const ::cache::proItem& item() const;
  inline ::cache::proItem* mutable_item();
  inline ::cache::proItem* release_item();
  inline void set_allocated_item(::cache::proItem* item);

  // @@protoc_insertion_point(class_scope:cache.proRemoveItem)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_item();
  inline void clear_has_item();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proItem* item_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proRemoveItem* default_instance_;
};
// -------------------------------------------------------------------

class proRemoveItems : public ::google::protobuf::Message {
 public:
  proRemoveItems();
  virtual ~proRemoveItems();

  proRemoveItems(const proRemoveItems& from);

  inline proRemoveItems& operator=(const proRemoveItems& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proRemoveItems& default_instance();

  void Swap(proRemoveItems* other);

  // implements Message ----------------------------------------------

  proRemoveItems* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proRemoveItems& from);
  void MergeFrom(const proRemoveItems& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated .cache.proItem items = 2;
  inline int items_size() const;
  inline void clear_items();
  static const int kItemsFieldNumber = 2;
  inline const ::cache::proItem& items(int index) const;
  inline ::cache::proItem* mutable_items(int index);
  inline ::cache::proItem* add_items();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proItem >&
      items() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proItem >*
      mutable_items();

  // @@protoc_insertion_point(class_scope:cache.proRemoveItems)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proItem > items_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proRemoveItems* default_instance_;
};
// -------------------------------------------------------------------

class proItemRes : public ::google::protobuf::Message {
 public:
  proItemRes();
  virtual ~proItemRes();

  proItemRes(const proItemRes& from);

  inline proItemRes& operator=(const proItemRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proItemRes& default_instance();

  void Swap(proItemRes* other);

  // implements Message ----------------------------------------------

  proItemRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proItemRes& from);
  void MergeFrom(const proItemRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 code() const;
  inline void set_code(::google::protobuf::uint32 value);

  // optional .cache.proItem item = 2;
  inline bool has_item() const;
  inline void clear_item();
  static const int kItemFieldNumber = 2;
  inline const ::cache::proItem& item() const;
  inline ::cache::proItem* mutable_item();
  inline ::cache::proItem* release_item();
  inline void set_allocated_item(::cache::proItem* item);

  // @@protoc_insertion_point(class_scope:cache.proItemRes)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_item();
  inline void clear_has_item();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proItem* item_;
  ::google::protobuf::uint32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proItemRes* default_instance_;
};
// -------------------------------------------------------------------

class proItemsRes : public ::google::protobuf::Message {
 public:
  proItemsRes();
  virtual ~proItemsRes();

  proItemsRes(const proItemsRes& from);

  inline proItemsRes& operator=(const proItemsRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proItemsRes& default_instance();

  void Swap(proItemsRes* other);

  // implements Message ----------------------------------------------

  proItemsRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proItemsRes& from);
  void MergeFrom(const proItemsRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 code() const;
  inline void set_code(::google::protobuf::uint32 value);

  // repeated .cache.proItem items = 2;
  inline int items_size() const;
  inline void clear_items();
  static const int kItemsFieldNumber = 2;
  inline const ::cache::proItem& items(int index) const;
  inline ::cache::proItem* mutable_items(int index);
  inline ::cache::proItem* add_items();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proItem >&
      items() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proItem >*
      mutable_items();

  // @@protoc_insertion_point(class_scope:cache.proItemsRes)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proItem > items_;
  ::google::protobuf::uint32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_item_2eproto();
  friend void protobuf_AssignDesc_item_2eproto();
  friend void protobuf_ShutdownFile_item_2eproto();

  void InitAsDefaultInstance();
  static proItemsRes* default_instance_;
};
// ===================================================================


// ===================================================================

// proItem

// required uint32 item_id = 1;
inline bool proItem::has_item_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proItem::set_has_item_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proItem::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proItem::clear_item_id() {
  item_id_ = 0u;
  clear_has_item_id();
}
inline ::google::protobuf::uint32 proItem::item_id() const {
  return item_id_;
}
inline void proItem::set_item_id(::google::protobuf::uint32 value) {
  set_has_item_id();
  item_id_ = value;
}

// required uint32 num = 2;
inline bool proItem::has_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proItem::set_has_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proItem::clear_has_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proItem::clear_num() {
  num_ = 0u;
  clear_has_num();
}
inline ::google::protobuf::uint32 proItem::num() const {
  return num_;
}
inline void proItem::set_num(::google::protobuf::uint32 value) {
  set_has_num();
  num_ = value;
}

// -------------------------------------------------------------------

// proGetItem

// required uint32 user_id = 1;
inline bool proGetItem::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proGetItem::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proGetItem::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proGetItem::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proGetItem::user_id() const {
  return user_id_;
}
inline void proGetItem::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required uint32 item_id = 2;
inline bool proGetItem::has_item_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proGetItem::set_has_item_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proGetItem::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proGetItem::clear_item_id() {
  item_id_ = 0u;
  clear_has_item_id();
}
inline ::google::protobuf::uint32 proGetItem::item_id() const {
  return item_id_;
}
inline void proGetItem::set_item_id(::google::protobuf::uint32 value) {
  set_has_item_id();
  item_id_ = value;
}

// -------------------------------------------------------------------

// proGetItems

// required uint32 user_id = 1;
inline bool proGetItems::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proGetItems::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proGetItems::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proGetItems::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proGetItems::user_id() const {
  return user_id_;
}
inline void proGetItems::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// -------------------------------------------------------------------

// proAddItem

// required uint32 user_id = 1;
inline bool proAddItem::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proAddItem::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proAddItem::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proAddItem::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proAddItem::user_id() const {
  return user_id_;
}
inline void proAddItem::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required .cache.proItem item = 2;
inline bool proAddItem::has_item() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proAddItem::set_has_item() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proAddItem::clear_has_item() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proAddItem::clear_item() {
  if (item_ != NULL) item_->::cache::proItem::Clear();
  clear_has_item();
}
inline const ::cache::proItem& proAddItem::item() const {
  return item_ != NULL ? *item_ : *default_instance_->item_;
}
inline ::cache::proItem* proAddItem::mutable_item() {
  set_has_item();
  if (item_ == NULL) item_ = new ::cache::proItem;
  return item_;
}
inline ::cache::proItem* proAddItem::release_item() {
  clear_has_item();
  ::cache::proItem* temp = item_;
  item_ = NULL;
  return temp;
}
inline void proAddItem::set_allocated_item(::cache::proItem* item) {
  delete item_;
  item_ = item;
  if (item) {
    set_has_item();
  } else {
    clear_has_item();
  }
}

// -------------------------------------------------------------------

// proAddItems

// required uint32 user_id = 1;
inline bool proAddItems::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proAddItems::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proAddItems::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proAddItems::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proAddItems::user_id() const {
  return user_id_;
}
inline void proAddItems::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .cache.proItem items = 2;
inline int proAddItems::items_size() const {
  return items_.size();
}
inline void proAddItems::clear_items() {
  items_.Clear();
}
inline const ::cache::proItem& proAddItems::items(int index) const {
  return items_.Get(index);
}
inline ::cache::proItem* proAddItems::mutable_items(int index) {
  return items_.Mutable(index);
}
inline ::cache::proItem* proAddItems::add_items() {
  return items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proItem >&
proAddItems::items() const {
  return items_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proItem >*
proAddItems::mutable_items() {
  return &items_;
}

// -------------------------------------------------------------------

// proRemoveItem

// required uint32 user_id = 1;
inline bool proRemoveItem::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proRemoveItem::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proRemoveItem::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proRemoveItem::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proRemoveItem::user_id() const {
  return user_id_;
}
inline void proRemoveItem::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required .cache.proItem item = 2;
inline bool proRemoveItem::has_item() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proRemoveItem::set_has_item() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proRemoveItem::clear_has_item() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proRemoveItem::clear_item() {
  if (item_ != NULL) item_->::cache::proItem::Clear();
  clear_has_item();
}
inline const ::cache::proItem& proRemoveItem::item() const {
  return item_ != NULL ? *item_ : *default_instance_->item_;
}
inline ::cache::proItem* proRemoveItem::mutable_item() {
  set_has_item();
  if (item_ == NULL) item_ = new ::cache::proItem;
  return item_;
}
inline ::cache::proItem* proRemoveItem::release_item() {
  clear_has_item();
  ::cache::proItem* temp = item_;
  item_ = NULL;
  return temp;
}
inline void proRemoveItem::set_allocated_item(::cache::proItem* item) {
  delete item_;
  item_ = item;
  if (item) {
    set_has_item();
  } else {
    clear_has_item();
  }
}

// -------------------------------------------------------------------

// proRemoveItems

// required uint32 user_id = 1;
inline bool proRemoveItems::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proRemoveItems::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proRemoveItems::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proRemoveItems::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proRemoveItems::user_id() const {
  return user_id_;
}
inline void proRemoveItems::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .cache.proItem items = 2;
inline int proRemoveItems::items_size() const {
  return items_.size();
}
inline void proRemoveItems::clear_items() {
  items_.Clear();
}
inline const ::cache::proItem& proRemoveItems::items(int index) const {
  return items_.Get(index);
}
inline ::cache::proItem* proRemoveItems::mutable_items(int index) {
  return items_.Mutable(index);
}
inline ::cache::proItem* proRemoveItems::add_items() {
  return items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proItem >&
proRemoveItems::items() const {
  return items_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proItem >*
proRemoveItems::mutable_items() {
  return &items_;
}

// -------------------------------------------------------------------

// proItemRes

// required uint32 code = 1;
inline bool proItemRes::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proItemRes::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proItemRes::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proItemRes::clear_code() {
  code_ = 0u;
  clear_has_code();
}
inline ::google::protobuf::uint32 proItemRes::code() const {
  return code_;
}
inline void proItemRes::set_code(::google::protobuf::uint32 value) {
  set_has_code();
  code_ = value;
}

// optional .cache.proItem item = 2;
inline bool proItemRes::has_item() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proItemRes::set_has_item() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proItemRes::clear_has_item() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proItemRes::clear_item() {
  if (item_ != NULL) item_->::cache::proItem::Clear();
  clear_has_item();
}
inline const ::cache::proItem& proItemRes::item() const {
  return item_ != NULL ? *item_ : *default_instance_->item_;
}
inline ::cache::proItem* proItemRes::mutable_item() {
  set_has_item();
  if (item_ == NULL) item_ = new ::cache::proItem;
  return item_;
}
inline ::cache::proItem* proItemRes::release_item() {
  clear_has_item();
  ::cache::proItem* temp = item_;
  item_ = NULL;
  return temp;
}
inline void proItemRes::set_allocated_item(::cache::proItem* item) {
  delete item_;
  item_ = item;
  if (item) {
    set_has_item();
  } else {
    clear_has_item();
  }
}

// -------------------------------------------------------------------

// proItemsRes

// required uint32 code = 1;
inline bool proItemsRes::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proItemsRes::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proItemsRes::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proItemsRes::clear_code() {
  code_ = 0u;
  clear_has_code();
}
inline ::google::protobuf::uint32 proItemsRes::code() const {
  return code_;
}
inline void proItemsRes::set_code(::google::protobuf::uint32 value) {
  set_has_code();
  code_ = value;
}

// repeated .cache.proItem items = 2;
inline int proItemsRes::items_size() const {
  return items_.size();
}
inline void proItemsRes::clear_items() {
  items_.Clear();
}
inline const ::cache::proItem& proItemsRes::items(int index) const {
  return items_.Get(index);
}
inline ::cache::proItem* proItemsRes::mutable_items(int index) {
  return items_.Mutable(index);
}
inline ::cache::proItem* proItemsRes::add_items() {
  return items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proItem >&
proItemsRes::items() const {
  return items_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proItem >*
proItemsRes::mutable_items() {
  return &items_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cache

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_item_2eproto__INCLUDED
