// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soul.proto

#ifndef PROTOBUF_soul_2eproto__INCLUDED
#define PROTOBUF_soul_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cache {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_soul_2eproto();
void protobuf_AssignDesc_soul_2eproto();
void protobuf_ShutdownFile_soul_2eproto();

class proSoul;
class proGetSoul;
class proGetSouls;
class proAddSoul;
class proAddSouls;
class proRemoveSoul;
class proRemoveSouls;
class proSoulRes;
class proSoulsRes;

// ===================================================================

class proSoul : public ::google::protobuf::Message {
 public:
  proSoul();
  virtual ~proSoul();

  proSoul(const proSoul& from);

  inline proSoul& operator=(const proSoul& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proSoul& default_instance();

  void Swap(proSoul* other);

  // implements Message ----------------------------------------------

  proSoul* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proSoul& from);
  void MergeFrom(const proSoul& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 soul_id = 1;
  inline bool has_soul_id() const;
  inline void clear_soul_id();
  static const int kSoulIdFieldNumber = 1;
  inline ::google::protobuf::uint32 soul_id() const;
  inline void set_soul_id(::google::protobuf::uint32 value);

  // required uint32 num = 2;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 2;
  inline ::google::protobuf::uint32 num() const;
  inline void set_num(::google::protobuf::uint32 value);

  // required uint32 protect_ts = 3;
  inline bool has_protect_ts() const;
  inline void clear_protect_ts();
  static const int kProtectTsFieldNumber = 3;
  inline ::google::protobuf::uint32 protect_ts() const;
  inline void set_protect_ts(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cache.proSoul)
 private:
  inline void set_has_soul_id();
  inline void clear_has_soul_id();
  inline void set_has_num();
  inline void clear_has_num();
  inline void set_has_protect_ts();
  inline void clear_has_protect_ts();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 soul_id_;
  ::google::protobuf::uint32 num_;
  ::google::protobuf::uint32 protect_ts_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proSoul* default_instance_;
};
// -------------------------------------------------------------------

class proGetSoul : public ::google::protobuf::Message {
 public:
  proGetSoul();
  virtual ~proGetSoul();

  proGetSoul(const proGetSoul& from);

  inline proGetSoul& operator=(const proGetSoul& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proGetSoul& default_instance();

  void Swap(proGetSoul* other);

  // implements Message ----------------------------------------------

  proGetSoul* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proGetSoul& from);
  void MergeFrom(const proGetSoul& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required uint32 soul_id = 2;
  inline bool has_soul_id() const;
  inline void clear_soul_id();
  static const int kSoulIdFieldNumber = 2;
  inline ::google::protobuf::uint32 soul_id() const;
  inline void set_soul_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:cache.proGetSoul)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_soul_id();
  inline void clear_has_soul_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 user_id_;
  ::google::protobuf::uint32 soul_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proGetSoul* default_instance_;
};
// -------------------------------------------------------------------

class proGetSouls : public ::google::protobuf::Message {
 public:
  proGetSouls();
  virtual ~proGetSouls();

  proGetSouls(const proGetSouls& from);

  inline proGetSouls& operator=(const proGetSouls& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proGetSouls& default_instance();

  void Swap(proGetSouls* other);

  // implements Message ----------------------------------------------

  proGetSouls* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proGetSouls& from);
  void MergeFrom(const proGetSouls& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated uint32 souls = 2;
  inline int souls_size() const;
  inline void clear_souls();
  static const int kSoulsFieldNumber = 2;
  inline ::google::protobuf::uint32 souls(int index) const;
  inline void set_souls(int index, ::google::protobuf::uint32 value);
  inline void add_souls(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      souls() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_souls();

  // @@protoc_insertion_point(class_scope:cache.proGetSouls)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > souls_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proGetSouls* default_instance_;
};
// -------------------------------------------------------------------

class proAddSoul : public ::google::protobuf::Message {
 public:
  proAddSoul();
  virtual ~proAddSoul();

  proAddSoul(const proAddSoul& from);

  inline proAddSoul& operator=(const proAddSoul& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proAddSoul& default_instance();

  void Swap(proAddSoul* other);

  // implements Message ----------------------------------------------

  proAddSoul* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proAddSoul& from);
  void MergeFrom(const proAddSoul& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required .cache.proSoul soul = 2;
  inline bool has_soul() const;
  inline void clear_soul();
  static const int kSoulFieldNumber = 2;
  inline const ::cache::proSoul& soul() const;
  inline ::cache::proSoul* mutable_soul();
  inline ::cache::proSoul* release_soul();
  inline void set_allocated_soul(::cache::proSoul* soul);

  // @@protoc_insertion_point(class_scope:cache.proAddSoul)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_soul();
  inline void clear_has_soul();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proSoul* soul_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proAddSoul* default_instance_;
};
// -------------------------------------------------------------------

class proAddSouls : public ::google::protobuf::Message {
 public:
  proAddSouls();
  virtual ~proAddSouls();

  proAddSouls(const proAddSouls& from);

  inline proAddSouls& operator=(const proAddSouls& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proAddSouls& default_instance();

  void Swap(proAddSouls* other);

  // implements Message ----------------------------------------------

  proAddSouls* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proAddSouls& from);
  void MergeFrom(const proAddSouls& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated .cache.proSoul souls = 2;
  inline int souls_size() const;
  inline void clear_souls();
  static const int kSoulsFieldNumber = 2;
  inline const ::cache::proSoul& souls(int index) const;
  inline ::cache::proSoul* mutable_souls(int index);
  inline ::cache::proSoul* add_souls();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proSoul >&
      souls() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proSoul >*
      mutable_souls();

  // @@protoc_insertion_point(class_scope:cache.proAddSouls)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proSoul > souls_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proAddSouls* default_instance_;
};
// -------------------------------------------------------------------

class proRemoveSoul : public ::google::protobuf::Message {
 public:
  proRemoveSoul();
  virtual ~proRemoveSoul();

  proRemoveSoul(const proRemoveSoul& from);

  inline proRemoveSoul& operator=(const proRemoveSoul& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proRemoveSoul& default_instance();

  void Swap(proRemoveSoul* other);

  // implements Message ----------------------------------------------

  proRemoveSoul* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proRemoveSoul& from);
  void MergeFrom(const proRemoveSoul& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required .cache.proSoul soul = 2;
  inline bool has_soul() const;
  inline void clear_soul();
  static const int kSoulFieldNumber = 2;
  inline const ::cache::proSoul& soul() const;
  inline ::cache::proSoul* mutable_soul();
  inline ::cache::proSoul* release_soul();
  inline void set_allocated_soul(::cache::proSoul* soul);

  // @@protoc_insertion_point(class_scope:cache.proRemoveSoul)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_soul();
  inline void clear_has_soul();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proSoul* soul_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proRemoveSoul* default_instance_;
};
// -------------------------------------------------------------------

class proRemoveSouls : public ::google::protobuf::Message {
 public:
  proRemoveSouls();
  virtual ~proRemoveSouls();

  proRemoveSouls(const proRemoveSouls& from);

  inline proRemoveSouls& operator=(const proRemoveSouls& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proRemoveSouls& default_instance();

  void Swap(proRemoveSouls* other);

  // implements Message ----------------------------------------------

  proRemoveSouls* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proRemoveSouls& from);
  void MergeFrom(const proRemoveSouls& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // repeated .cache.proSoul souls = 2;
  inline int souls_size() const;
  inline void clear_souls();
  static const int kSoulsFieldNumber = 2;
  inline const ::cache::proSoul& souls(int index) const;
  inline ::cache::proSoul* mutable_souls(int index);
  inline ::cache::proSoul* add_souls();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proSoul >&
      souls() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proSoul >*
      mutable_souls();

  // @@protoc_insertion_point(class_scope:cache.proRemoveSouls)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proSoul > souls_;
  ::google::protobuf::uint32 user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proRemoveSouls* default_instance_;
};
// -------------------------------------------------------------------

class proSoulRes : public ::google::protobuf::Message {
 public:
  proSoulRes();
  virtual ~proSoulRes();

  proSoulRes(const proSoulRes& from);

  inline proSoulRes& operator=(const proSoulRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proSoulRes& default_instance();

  void Swap(proSoulRes* other);

  // implements Message ----------------------------------------------

  proSoulRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proSoulRes& from);
  void MergeFrom(const proSoulRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 code() const;
  inline void set_code(::google::protobuf::uint32 value);

  // optional .cache.proSoul soul = 2;
  inline bool has_soul() const;
  inline void clear_soul();
  static const int kSoulFieldNumber = 2;
  inline const ::cache::proSoul& soul() const;
  inline ::cache::proSoul* mutable_soul();
  inline ::cache::proSoul* release_soul();
  inline void set_allocated_soul(::cache::proSoul* soul);

  // @@protoc_insertion_point(class_scope:cache.proSoulRes)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_soul();
  inline void clear_has_soul();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::cache::proSoul* soul_;
  ::google::protobuf::uint32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proSoulRes* default_instance_;
};
// -------------------------------------------------------------------

class proSoulsRes : public ::google::protobuf::Message {
 public:
  proSoulsRes();
  virtual ~proSoulsRes();

  proSoulsRes(const proSoulsRes& from);

  inline proSoulsRes& operator=(const proSoulsRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const proSoulsRes& default_instance();

  void Swap(proSoulsRes* other);

  // implements Message ----------------------------------------------

  proSoulsRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const proSoulsRes& from);
  void MergeFrom(const proSoulsRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::uint32 code() const;
  inline void set_code(::google::protobuf::uint32 value);

  // repeated .cache.proSoul souls = 2;
  inline int souls_size() const;
  inline void clear_souls();
  static const int kSoulsFieldNumber = 2;
  inline const ::cache::proSoul& souls(int index) const;
  inline ::cache::proSoul* mutable_souls(int index);
  inline ::cache::proSoul* add_souls();
  inline const ::google::protobuf::RepeatedPtrField< ::cache::proSoul >&
      souls() const;
  inline ::google::protobuf::RepeatedPtrField< ::cache::proSoul >*
      mutable_souls();

  // @@protoc_insertion_point(class_scope:cache.proSoulsRes)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::cache::proSoul > souls_;
  ::google::protobuf::uint32 code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_soul_2eproto();
  friend void protobuf_AssignDesc_soul_2eproto();
  friend void protobuf_ShutdownFile_soul_2eproto();

  void InitAsDefaultInstance();
  static proSoulsRes* default_instance_;
};
// ===================================================================


// ===================================================================

// proSoul

// required uint32 soul_id = 1;
inline bool proSoul::has_soul_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proSoul::set_has_soul_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proSoul::clear_has_soul_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proSoul::clear_soul_id() {
  soul_id_ = 0u;
  clear_has_soul_id();
}
inline ::google::protobuf::uint32 proSoul::soul_id() const {
  return soul_id_;
}
inline void proSoul::set_soul_id(::google::protobuf::uint32 value) {
  set_has_soul_id();
  soul_id_ = value;
}

// required uint32 num = 2;
inline bool proSoul::has_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proSoul::set_has_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proSoul::clear_has_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proSoul::clear_num() {
  num_ = 0u;
  clear_has_num();
}
inline ::google::protobuf::uint32 proSoul::num() const {
  return num_;
}
inline void proSoul::set_num(::google::protobuf::uint32 value) {
  set_has_num();
  num_ = value;
}

// required uint32 protect_ts = 3;
inline bool proSoul::has_protect_ts() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void proSoul::set_has_protect_ts() {
  _has_bits_[0] |= 0x00000004u;
}
inline void proSoul::clear_has_protect_ts() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void proSoul::clear_protect_ts() {
  protect_ts_ = 0u;
  clear_has_protect_ts();
}
inline ::google::protobuf::uint32 proSoul::protect_ts() const {
  return protect_ts_;
}
inline void proSoul::set_protect_ts(::google::protobuf::uint32 value) {
  set_has_protect_ts();
  protect_ts_ = value;
}

// -------------------------------------------------------------------

// proGetSoul

// required uint32 user_id = 1;
inline bool proGetSoul::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proGetSoul::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proGetSoul::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proGetSoul::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proGetSoul::user_id() const {
  return user_id_;
}
inline void proGetSoul::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required uint32 soul_id = 2;
inline bool proGetSoul::has_soul_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proGetSoul::set_has_soul_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proGetSoul::clear_has_soul_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proGetSoul::clear_soul_id() {
  soul_id_ = 0u;
  clear_has_soul_id();
}
inline ::google::protobuf::uint32 proGetSoul::soul_id() const {
  return soul_id_;
}
inline void proGetSoul::set_soul_id(::google::protobuf::uint32 value) {
  set_has_soul_id();
  soul_id_ = value;
}

// -------------------------------------------------------------------

// proGetSouls

// required uint32 user_id = 1;
inline bool proGetSouls::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proGetSouls::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proGetSouls::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proGetSouls::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proGetSouls::user_id() const {
  return user_id_;
}
inline void proGetSouls::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated uint32 souls = 2;
inline int proGetSouls::souls_size() const {
  return souls_.size();
}
inline void proGetSouls::clear_souls() {
  souls_.Clear();
}
inline ::google::protobuf::uint32 proGetSouls::souls(int index) const {
  return souls_.Get(index);
}
inline void proGetSouls::set_souls(int index, ::google::protobuf::uint32 value) {
  souls_.Set(index, value);
}
inline void proGetSouls::add_souls(::google::protobuf::uint32 value) {
  souls_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
proGetSouls::souls() const {
  return souls_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
proGetSouls::mutable_souls() {
  return &souls_;
}

// -------------------------------------------------------------------

// proAddSoul

// required uint32 user_id = 1;
inline bool proAddSoul::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proAddSoul::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proAddSoul::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proAddSoul::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proAddSoul::user_id() const {
  return user_id_;
}
inline void proAddSoul::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required .cache.proSoul soul = 2;
inline bool proAddSoul::has_soul() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proAddSoul::set_has_soul() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proAddSoul::clear_has_soul() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proAddSoul::clear_soul() {
  if (soul_ != NULL) soul_->::cache::proSoul::Clear();
  clear_has_soul();
}
inline const ::cache::proSoul& proAddSoul::soul() const {
  return soul_ != NULL ? *soul_ : *default_instance_->soul_;
}
inline ::cache::proSoul* proAddSoul::mutable_soul() {
  set_has_soul();
  if (soul_ == NULL) soul_ = new ::cache::proSoul;
  return soul_;
}
inline ::cache::proSoul* proAddSoul::release_soul() {
  clear_has_soul();
  ::cache::proSoul* temp = soul_;
  soul_ = NULL;
  return temp;
}
inline void proAddSoul::set_allocated_soul(::cache::proSoul* soul) {
  delete soul_;
  soul_ = soul;
  if (soul) {
    set_has_soul();
  } else {
    clear_has_soul();
  }
}

// -------------------------------------------------------------------

// proAddSouls

// required uint32 user_id = 1;
inline bool proAddSouls::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proAddSouls::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proAddSouls::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proAddSouls::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proAddSouls::user_id() const {
  return user_id_;
}
inline void proAddSouls::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .cache.proSoul souls = 2;
inline int proAddSouls::souls_size() const {
  return souls_.size();
}
inline void proAddSouls::clear_souls() {
  souls_.Clear();
}
inline const ::cache::proSoul& proAddSouls::souls(int index) const {
  return souls_.Get(index);
}
inline ::cache::proSoul* proAddSouls::mutable_souls(int index) {
  return souls_.Mutable(index);
}
inline ::cache::proSoul* proAddSouls::add_souls() {
  return souls_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proSoul >&
proAddSouls::souls() const {
  return souls_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proSoul >*
proAddSouls::mutable_souls() {
  return &souls_;
}

// -------------------------------------------------------------------

// proRemoveSoul

// required uint32 user_id = 1;
inline bool proRemoveSoul::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proRemoveSoul::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proRemoveSoul::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proRemoveSoul::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proRemoveSoul::user_id() const {
  return user_id_;
}
inline void proRemoveSoul::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required .cache.proSoul soul = 2;
inline bool proRemoveSoul::has_soul() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proRemoveSoul::set_has_soul() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proRemoveSoul::clear_has_soul() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proRemoveSoul::clear_soul() {
  if (soul_ != NULL) soul_->::cache::proSoul::Clear();
  clear_has_soul();
}
inline const ::cache::proSoul& proRemoveSoul::soul() const {
  return soul_ != NULL ? *soul_ : *default_instance_->soul_;
}
inline ::cache::proSoul* proRemoveSoul::mutable_soul() {
  set_has_soul();
  if (soul_ == NULL) soul_ = new ::cache::proSoul;
  return soul_;
}
inline ::cache::proSoul* proRemoveSoul::release_soul() {
  clear_has_soul();
  ::cache::proSoul* temp = soul_;
  soul_ = NULL;
  return temp;
}
inline void proRemoveSoul::set_allocated_soul(::cache::proSoul* soul) {
  delete soul_;
  soul_ = soul;
  if (soul) {
    set_has_soul();
  } else {
    clear_has_soul();
  }
}

// -------------------------------------------------------------------

// proRemoveSouls

// required uint32 user_id = 1;
inline bool proRemoveSouls::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proRemoveSouls::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proRemoveSouls::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proRemoveSouls::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 proRemoveSouls::user_id() const {
  return user_id_;
}
inline void proRemoveSouls::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated .cache.proSoul souls = 2;
inline int proRemoveSouls::souls_size() const {
  return souls_.size();
}
inline void proRemoveSouls::clear_souls() {
  souls_.Clear();
}
inline const ::cache::proSoul& proRemoveSouls::souls(int index) const {
  return souls_.Get(index);
}
inline ::cache::proSoul* proRemoveSouls::mutable_souls(int index) {
  return souls_.Mutable(index);
}
inline ::cache::proSoul* proRemoveSouls::add_souls() {
  return souls_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proSoul >&
proRemoveSouls::souls() const {
  return souls_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proSoul >*
proRemoveSouls::mutable_souls() {
  return &souls_;
}

// -------------------------------------------------------------------

// proSoulRes

// required uint32 code = 1;
inline bool proSoulRes::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proSoulRes::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proSoulRes::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proSoulRes::clear_code() {
  code_ = 0u;
  clear_has_code();
}
inline ::google::protobuf::uint32 proSoulRes::code() const {
  return code_;
}
inline void proSoulRes::set_code(::google::protobuf::uint32 value) {
  set_has_code();
  code_ = value;
}

// optional .cache.proSoul soul = 2;
inline bool proSoulRes::has_soul() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void proSoulRes::set_has_soul() {
  _has_bits_[0] |= 0x00000002u;
}
inline void proSoulRes::clear_has_soul() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void proSoulRes::clear_soul() {
  if (soul_ != NULL) soul_->::cache::proSoul::Clear();
  clear_has_soul();
}
inline const ::cache::proSoul& proSoulRes::soul() const {
  return soul_ != NULL ? *soul_ : *default_instance_->soul_;
}
inline ::cache::proSoul* proSoulRes::mutable_soul() {
  set_has_soul();
  if (soul_ == NULL) soul_ = new ::cache::proSoul;
  return soul_;
}
inline ::cache::proSoul* proSoulRes::release_soul() {
  clear_has_soul();
  ::cache::proSoul* temp = soul_;
  soul_ = NULL;
  return temp;
}
inline void proSoulRes::set_allocated_soul(::cache::proSoul* soul) {
  delete soul_;
  soul_ = soul;
  if (soul) {
    set_has_soul();
  } else {
    clear_has_soul();
  }
}

// -------------------------------------------------------------------

// proSoulsRes

// required uint32 code = 1;
inline bool proSoulsRes::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void proSoulsRes::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void proSoulsRes::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void proSoulsRes::clear_code() {
  code_ = 0u;
  clear_has_code();
}
inline ::google::protobuf::uint32 proSoulsRes::code() const {
  return code_;
}
inline void proSoulsRes::set_code(::google::protobuf::uint32 value) {
  set_has_code();
  code_ = value;
}

// repeated .cache.proSoul souls = 2;
inline int proSoulsRes::souls_size() const {
  return souls_.size();
}
inline void proSoulsRes::clear_souls() {
  souls_.Clear();
}
inline const ::cache::proSoul& proSoulsRes::souls(int index) const {
  return souls_.Get(index);
}
inline ::cache::proSoul* proSoulsRes::mutable_souls(int index) {
  return souls_.Mutable(index);
}
inline ::cache::proSoul* proSoulsRes::add_souls() {
  return souls_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::cache::proSoul >&
proSoulsRes::souls() const {
  return souls_;
}
inline ::google::protobuf::RepeatedPtrField< ::cache::proSoul >*
proSoulsRes::mutable_souls() {
  return &souls_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cache

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_soul_2eproto__INCLUDED
